### ISSUE TITLE
Nuke Ops fail even if they succeed

### ISSUE THREAD

**Issue by The1BloodMaster** [unitystation/unitystation#2863] opened 2020-02-03 17:26 UTC
https://cdn.discordapp.com/attachments/667287667121061908/673939383354785801/Thing_4.jpg

### Steps to Reproduce:

1.  Win as nuclear ops

**Comment by DooblyNoobly** [comment] 2020-02-04 04:34
cannot reproduce on build 4000. closing

**Comment by fomalsd** [comment] 2020-02-06 15:13
Still a thing on 4006

**Comment by Evan-R-Rogers** [comment] 2020-02-08 12:53
Now, are the Nukies the ones setting off the bomb or the crew after learning the code? I've only had one round where the Nukies actually got the bomb, they one, all other rounds the crew put in the code thus blowing up the station yet the Nukies still 'lost'.

**Comment by myrmecoleonn** [comment] 2020-02-08 13:09
I've set the nuke off as the nukie twice and had myself redtext; could be only occasional instances but I've yet to see a greentext from the nukies

**Comment by fomalsd** [comment] 2020-02-15 21:30
fixed

**Closed as completed by fomalsd** 2020-02-15 21:30 UTC
Labels: Type: Bug
