### ISSUE TITLE
Taking at least 40 dmg to the chest makes you start suffocating

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#7576] opened 2021-10-15 17:14 UTC
### Environment
- Game Version: Win10
- OS Version: 21101020 (latest at the moment of writing)

### Detailed description of bug

As stated in the title, whenever you take at least 40  brute damage to the chest you start suffocating and there is nothing you can do about it. I also had an instance where my *torso dislocated*

### Steps to reproduce
1. Login to staging
2. Hit yourself a couple times in the chest
3. Use health scanner and stop when you have at leat 40 damage
3. start suffocating

**Comment by JustinTrotter** [comment] 2021-10-15 19:21
Reproduced. 
SWAG: I think the lungs are getting damaged when they shouldn't.

**Comment by PerfectTangent** [comment] 2021-10-15 19:24
I think the lungs are getting damaged when they _should._ Some amount of damage that a body part takes is passed to the organs contained within the body part. It's likely that 40 damage on the body part is enough to start impacting the functioning of the lungs. This might be a non-issue.

torso dislocation is a different matter, though.

**Comment by JustinTrotter** [comment] 2021-10-15 19:46
I think the issue is that the lungs are taking too much damage then. 40 damage is like 3 or 4 toolbox swings to an unarmored target. Getting internal damage that is unhealable outside of surgery is a big problem.

**Comment by PerfectTangent** [comment] 2021-10-15 19:57
it will heal itself over time. there's natural healing for every organ afaik. I'm curious how much are the lungs actually impacted by the damage. It could be that the O2 warning is appearing when there's hardly an issue at all.

**Comment by Leander-0** [comment] 2021-10-15 21:05
atleast right now i doesnt heal itseft over time, actually once you reach the 40 damage mark you have 1:30 seconds before you fall into soft-crit, if you dont heal the wound you will basically die or you will die faster if someone keeps hitting you.


https://user-images.githubusercontent.com/80334192/137553186-6f1bd6bf-933c-473b-b5bd-9655199db5b0.mp4


also IRL there is the ribcage(not implemented) so actually your ribs should break before the lungs, maybe there could be a chance for one of your ribs to puncture the lungs?

**Comment by Leander-0** [comment] 2021-10-16 23:12
adding this here so it doesnt get lost.

basically when your chest gets hit with ANY kind of damage you will start suffocating no matter what.

proof for toxin damage:

https://user-images.githubusercontent.com/80334192/137604198-e3767fa6-abc6-4dfe-a10e-0703c52d3392.mp4

and proof for burn damage:

https://user-images.githubusercontent.com/80334192/137604203-96f6d564-49b4-498b-8f6b-c19fd0164303.mp4

im really sure 3rd degree burns dont make your lungs go haywire xD

**Comment by JustinTrotter** [comment] 2021-10-16 23:13
Gonna work on this tonight

**Comment by JustinTrotter** [comment] 2021-10-17 16:58
Finding the root cause of this is tougher than I thought. Still can’t figure out what is stopping circulation when damaged enough. 

It is not trauma damage, I’ve narrowed that down for sure last night. No organs are getting their health values lowered and the oxy damage is occurring while not firing any trauma damage calls (based on my debug logs)

It also doesn’t exactly occur with above 40 damage. It occurs when damaged after being above 25 damage, in otherwords when severity is “moderate” and then getting a hit.

I also noticed that after the important hit there’s a small delay (about 5 seconds) before oxy damage begins to accumulate.

The torso dislocation occurs when severity is high enough to have trauma damage. I think this caused by the bone organs breaking but it reporting that the torso is dislocating as if it’s a limb. This looks easily fixable.

Next I’m going to look at organ efficiency vs damage taken. I have a hunch it might be related to that.

**Comment by JustinTrotter** [comment] 2021-10-18 17:49
Found root cause: bloodSaturation

For some reason when you take damage to the torso, bloodSaturation slowly drops proportionally. Once bloodSaturation drops below .70, (when torso damage is above 30) the player starts taking oxy damage every tick.

Either something is corrupting the blood per hit, or the heart is somehow becoming proportionally less efficient when the torso is damaged.

Next step is to find how/where bloodSaturation is dropping.

**Comment by JustinTrotter** [comment] 2021-10-18 21:32
<img width="782" alt="Screen Shot 2021-10-18 at 4 11 41 PM" src="https://user-images.githubusercontent.com/8183999/137809307-aec4087e-7bfe-4e1d-b29d-ea1b5d0872b3.png">
<img width="558" alt="Screen Shot 2021-10-18 at 4 12 28 PM" src="https://user-images.githubusercontent.com/8183999/137809309-cdd76002-5974-4dad-8e93-c694fab548f6.png">

It looks like bloodCapacity isn't set correctly. This is directly affects how bloodSaturation is calculated. I'm not familiar enough the new health system to make any calls on what the proper configuration should be.

Right now it is 0.002 which makes circulation stop working at around 30+ damage
Setting it to 0.02 makes circulation stop work at around 80-90ish damage
Setting it to 0.2 causes circulation to continue working until soft crit.

Which is the proper setting?

**Comment by corp-0** [comment] 2021-10-18 21:38
so is the heart getting hurt when you get hit in the torso? Is it **every time** you receive damage in the torso?

**Comment by JustinTrotter** [comment] 2021-10-18 21:49
The heart organ itself isn't taking damage. From what I can tell there is a damage modifier applied to all sub organs that affects each organs efficiency.

<img width="594" alt="Screen Shot 2021-10-18 at 4 47 59 PM" src="https://user-images.githubusercontent.com/8183999/137811494-832290fc-dd35-4bb4-b3db-9d93f7204b68.png">
<img width="881" alt="Screen Shot 2021-10-18 at 4 50 55 PM" src="https://user-images.githubusercontent.com/8183999/137811718-3e7c7dab-19b6-42d9-971d-5695b4820fa4.png">


So for each damage the player sustains, the less blood is transferred per pump.

**Comment by corp-0** [comment] 2021-10-19 00:15
> The heart organ itself isn't taking damage. From what I can tell there is a damage modifier applied to all sub organs that affects each organs efficiency.
> 
> <img alt="Screen Shot 2021-10-18 at 4 47 59 PM" width="594" src="https://user-images.githubusercontent.com/8183999/137811494-832290fc-dd35-4bb4-b3db-9d93f7204b68.png">
> 
> <img alt="Screen Shot 2021-10-18 at 4 50 55 PM" width="881" src="https://user-images.githubusercontent.com/8183999/137811718-3e7c7dab-19b6-42d9-971d-5695b4820fa4.png">
> 
> So for each damage the player sustains, the less blood is transferred per pump.

effectiveness should indeed be modified but only after the organ itself got damaged

**Comment by JustinTrotter** [comment] 2021-10-19 00:34
> effectiveness should indeed be modified but only after the organ itself got damaged

Okay. I’ll update DoHeartBeat() to use the hearts health to reduce its effectiveness rather than the parent organ.

**Closed as completed** 2021-10-21 16:58 UTC
Labels: Type: Bug, System: Health
