### ISSUE TITLE
Fire should produce light.

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3123] opened 2020-02-15 11:56 UTC
It's annoying to be running around with the lights off, and accidentally running into a plasma fire you didn't see.

**Comment by NoooneyDude** [comment] 2020-07-23 08:26
This is a duplicate of #2581.

**Comment by corp-0** [comment] 2020-08-31 00:43
closing, fire now emits lights!

**Closed as completed by corp-0** 2020-08-31 00:43 UTC
Labels: Type: Feature, System: Atmos, System: Lighting
