### ISSUE TITLE
[Mapping]  fallstation et square station, terminal

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9024] opened 2022-07-31 14:44 UTC
### Detailed description of bug
There are no terminals on the walls of either station.

**Comment by MaxIsJoe** [comment] 2022-07-31 21:00
This is a duplicate of #8850

**Comment by MaxIsJoe** [comment] 2022-07-31 21:00
Also this is not considered a bug

**Closed as not planned** 2022-07-31 23:22 UTC
Labels: Type: Bug
