### ISSUE TITLE
Nuke disk teleportation

### ISSUE THREAD

**Issue by Humonitarian** [unitystation/unitystation#3825] opened 2020-04-03 23:43 UTC
# Issue Template

## Description
When inserted, instead of exploding the nuke disk teleports back on the station

### Detailed Bug Report
If you insert the nuke disk, then enter the code, click OK, then click the nuke disk symbol, the nuke will display "INSERT NUKE DISK" and refuse to explode. The nuke disk uses this chance to teleport back on the station.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Insert nuke disk in the nuke
2.  Type in code
3.  Click the "OK" button
4. Click the disk symbol

**Comment by ReiderJack** [comment] 2020-04-04 07:06
Where was the nuke when you ejected the disk?

**Comment by ReiderJack** [comment] 2020-04-04 07:13
> If you insert the nuke disk, then enter the code, click OK, then click the nuke disk symbol, the nuke will display "INSERT NUKE DISK" and refuse to explode. The nuke disk uses this chance to teleport back on the station.

Don't eject the disk before you set the timer. Disk gives you access to the nuke and ejecting it will clear out code you wrote.

**Comment by corp-0** [comment] 2020-04-06 02:35
You should close this issue as you accidentally ejected the disk which made it to teleport. Intended behavior.

**Comment by RedlineTriad** [comment] 2020-04-19 10:48
Is this because it's moved to hiddenpos or can it be closed?

**Closed as completed** 2020-04-19 10:50 UTC
Labels: Type: Bug
