### ISSUE TITLE
Traitor menu placeholder still exists

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6721] opened 2021-06-05 15:08 UTC
like, who's ever gonna get 999-

![image](https://user-images.githubusercontent.com/14188696/120896161-4b3b5500-c5ee-11eb-9796-8f80ca3fda0c.png)

**Comment by PetMudstone** [comment] 2021-07-10 13:52
I believe this was caused by #6756, which is now fixed. The image above might be from when .45 magazines were available to traitors for some reason which I resolved in #6757.

**Comment by PerfectTangent** [comment] 2021-10-07 14:39
Could not reproduce, Given what Pet said, I think this can be closed.

**Closed as completed by PerfectTangent** 2021-10-07 14:39 UTC
Labels: Type: Bug, Status: Needs Reproduction, ValidForContest
