### ISSUE TITLE
Unreal Emergency Shuttle does not dock correctly

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6581] opened 2021-05-19 15:41 UTC
Unreal Emergency Shuttle doesnt dock correctly and causes it to break when it arrives at centcom.

**Comment by PerfectTangent** [comment] 2021-05-19 15:42
Good stuff, as I predicted in #6421.

**Comment by corp-0** [comment] 2023-03-06 15:48
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

Also UnrealStation is currently abandoned.

**Closed as completed by corp-0** 2023-03-06 15:48 UTC
Labels: Type: Bug, No Coding, Group: Mapping
