### ISSUE TITLE
Ghosts don't always spawn over their dead bodies

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2780] opened 2020-01-29 04:01 UTC
For some reason you can end up spawning at your spawn point instead of the dead body point as a ghost. This is annoying as a nuke ops as you are spawned in the middle of no where. 

We need to a solution to ensure it always spawns over the dead body

**Comment by Mantle-Wanderer** [comment] 2020-01-29 23:21
I think this usually happens when your body was gibbed, since I've mostly seen it whenever I crash a shuttle into the station and get turned into a fine mist.

**Comment by fomalsd** [comment] 2020-01-29 23:35
yep, when your body is gibbed you start following a meat slab that's left of you, but when it's gone ghost only spawns at your last body's position (I think)

**Comment by JesterX666** [comment] 2020-02-02 15:51
It's curious, I can't reproduce it anymore.  My body is no longer vaporized when I crash into the station.

It is possible that I merged some code that prevents it from happening.

**Closed as completed** 2020-02-04 06:51 UTC
Labels: Type: Bug, Status: In Progress, Status: Needs Reproduction
