### ISSUE TITLE
Wrong death message when killed by gazillion pressure

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2669] opened 2020-01-19 16:53 UTC
When killed by a surge of pressure, it says you commited suicide.

![image](https://user-images.githubusercontent.com/32009105/72684851-0e7ec480-3ab2-11ea-82b8-696a5e2bb4c8.png)

Steps to Reproduce

1.  Open all valves in the atmos tech room
2.  Exit the room
3.  Come back a little later
4.  As soon as you open the door, you die -> ok
5.  You get the chat message that you commited suicide.  <- Not entirely true

**Comment by NoooneyDude** [comment] 2020-07-23 04:42
I couldn't reproduce this.

**Comment by PerfectTangent** [comment] 2021-05-09 09:08
I couldn't reproduce either. Closing for now.

**Closed as completed by PerfectTangent** 2021-05-09 09:08 UTC
Labels: Type: Bug, Priority: Low
