### ISSUE TITLE
Armor formula rework and reimplementation B:55

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6288] opened 2021-03-22 23:08 UTC
## Description

**This is a health related bounty.** This bounty calls for adding armor back into the game, which was commented out in the great health purge due to incompatibility with the new changes. Since armor needs to be readded to the game, now is a good opportunity to rework how it is calculated.

the old formula for armor was purely additive. Multiple armor sources protecting a particular body part would be added together, expressed as a percent, and multiplied against the damage. Example: if someone had 20 armor from one piece and 50 armor from another, they were added to make 70 armor, and that armor would reduce all damage to that body part by 70%.

Simply adding the armors together results in a couple undesireable situations, namely that you can get enough armor together to equal 100 or greater armor, in which case you are totally immune to damages of that type of armor.

The new formula should instead be proportionally added: a source of 20 armor reduces incoming damage by 20% and the second source of 50 armor should reduce the leftover damage afterwards by an additional 50%. 

_Initial damage * armor A, take the remaining damage * armor B, take the remaining remaining damage * armor C = damage dealt._

When expressed as an process of repeated multiplication, it does not matter which armor reduction is calculated first; you will always get the same results. This system also still allows devs and admins to make armor pieces that are totally immune to damage if that is desired by setting the armor value directly to 100. 

This formula rework also won't have much of an effect on the current game balance because there are not that many ways to stack armor at this time, but it will be a much easier thing to do in the future, so this formula helps future proof armor balance a bit.

Second, a important feature of weapons is the ability to penetrate armor. This is essentially anti-armor, subtracting from each source of armor before the armor is used in the same fashion that armor subtracts from the total damage.

## What is required to fulfill the bounty:

- [x] rework armor back into the game using the new formula described above
- [x] add armor penetration as a stat to weapons and projectiles.

**Comment by corp-0** [comment] 2021-03-22 23:22
Not quite sure if this is right, but pseudo coding the armor calculation might be something like

```cs
private float GetReducedDamage(float initialDamage)
{
    var damage = initialDamage;
    foreach (var armor in bodyPart.ArmorValues) //this would be a list of armor values that get added/removed during the game
    {
        damage *= armor;
    }
    return damage;
}
```

maybe you have a better approach @Bod9001 ?

**Comment by Bod9001** [comment] 2021-03-23 10:24
the problem is working out which slot the body part is related to, what happens if there's multiple body parts covered but that slot for example having extra arms

**Comment by corp-0** [comment] 2021-03-23 15:27
> the problem is working out which slot the body part is related to, what happens if there's multiple body parts covered but that slot for example having extra arms

This would work however wearable armor works since we don’t have slots related to body parts yet

**Comment by Lizurt** [comment] 2021-03-29 15:12
I'll try to reimplement it

**Comment by PerfectTangent** [comment] 2021-03-29 15:51
@Lizurt you want to tackle this?

**Comment by PerfectTangent** [comment] 2021-03-29 15:55
You have been assigned.

**Comment by Lizurt** [comment] 2021-03-29 15:56
> @Lizurt you want to tackle this?

Yep

> You have been assigned.

Thanks

**Comment by Bod9001** [comment] 2021-04-02 08:24
merged without checking like a dumdum

**Comment by Bod9001** [comment] 2021-04-02 08:33
nah, I'm just being a big double dumdum

**Closed as completed by Bod9001** 2021-04-02 08:33 UTC
Labels: Type: Feature, Bounty, Priority: High, System: Damage, Type: Balance
