### ISSUE TITLE
plasma fires

### ISSUE THREAD

**Issue by VernaSaurus** [unitystation/unitystation#4257] opened 2020-05-15 20:11 UTC
i dunno what you guys did but plasma fires are broken in staging
they refuse to light and now they don't even break glass _at all_

**Comment by AutumnNova** [comment] 2020-05-15 20:15
https://github.com/unitystation/unitystation/pull/4246

make sure your using the correct ratio (2 oxy:1 plasma)

**Comment by corp-0** [comment] 2020-05-15 20:15
Pet buffed windows armor from 80 to 99 because 80 was just inmediately melted and 99 took time, according to his tests. 

Plasma not igniting has always been tricky, some say it is the gas mix you need to use.

**Comment by VernaSaurus** [comment] 2020-05-15 20:16
ok, but like i said, plasma can no longer damage windows at all

**Comment by corp-0** [comment] 2020-05-15 20:24
try making a big fire first

**Comment by Fiftyllama** [comment] 2020-05-16 04:36
I did some testing on this as I consider myself a bit of a plasmafire conneuseur

While I was able to confirm that fires still break windows, they do seem to be a lot more unstable often receding after a brief expansion. 

Even with optimal conditions the plasmafire tends to stay in a very limited area and does not spread very well, even in situations where they would spread very well in earlier versions.

**Comment by laszlotuss** [comment] 2020-05-16 22:58
I just seen a quarter of a station burned down due to plasma fire twice in the last 2 hours.

**Comment by AutumnNova** [comment] 2020-05-17 12:32
might be that vents and scrubbers dont burn anymore

**Comment by Fiftyllama** [comment] 2020-05-17 17:45
whatever made them not work as well seems to have been fixed, since they now spread as before. So I'm pretty sure we can close this

**Comment by corp-0** [comment] 2020-05-17 19:07
it never broke, me thinks. Fire was always a little unpredictable in my opinion.

**Comment by Fiftyllama** [comment] 2020-05-17 20:12
when i tested the fire would barely fill engineering on outpost even with 3 cannisters and 6 oxytanks, and not spread at all even given the chance. but idk

**Comment by fomalsd** [comment] 2020-05-17 22:28
closing, feel free to reopen if you find a reliable way to reproduce it

**Closed as completed by fomalsd** 2020-05-17 22:28 UTC
Labels: Status: Needs Reproduction
