### ISSUE TITLE
Xenos can spawn already dead

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2638] opened 2020-01-18 03:25 UTC
## Description

Xenos can spawn dead due to not being pool safe.

1. Spawn a xeno using dev spawner.
2. Kill it.
3. Butcher it.
4. Spawn another xeno using dev spawner. It spawns dead. It should instead spawn as a healthy happy xeno.

This just requires implementing IServerSpawn or IServerDespawn interface on the appropriate component to ensure the xeno alive / dead / health status is properly initialized on spawn or despawn.

**Comment by corp-0** [comment] 2020-05-04 22:54
I kinda fixed this. They won't be dead because I reset all health values in #4042 

New problem is they often spawn brain dead, as in they won't do anything, despite reinitilizing their behavior in the same PR.

**Comment by NoooneyDude** [comment] 2020-07-23 03:07
Is this still an issue? I could not reproduce the dead xenomorph or braindead behaviour.

![xenomorph](https://user-images.githubusercontent.com/6926225/88248709-2d2a7600-ccf6-11ea-967b-7695c8401805.gif)

**Comment by corp-0** [comment] 2020-07-28 20:55
@NoooneyDude confirmed this to be fixed, closing

**Closed as completed by corp-0** 2020-07-28 20:55 UTC
Labels: Type: Bug, System: Lifecycle
