### ISSUE TITLE
Detonating nukes on non-nuclear emergency rounds prevents new rounds from starting.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5226] opened 2020-09-30 02:04 UTC
## Description
Title. If a nuke is detonated on a round that isn't set to the Nuclear Emergency game mode, then new rounds will not start properly after the current round ends due to a nuke going off. The timer will appear and it will count down, but once it hits zero it will not actually start the round. This is bad for when admins let the nuke go off, and this can only be resolved by resetting the server.

**Comment by Aranclanos** [comment] 2020-09-30 15:19
can't reproduce

**Comment by PerfectTangent** [comment] 2021-02-21 22:06
Tested with Jakesolly. Cannot reproduce, Closing.

**Closed as completed by PerfectTangent** 2021-02-21 22:06 UTC
Labels: Type: Bug, Status: Needs Reproduction
