### ISSUE TITLE
Satchel/duffel/backpack character preference is ignored

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9398] opened 2022-11-29 03:39 UTC
### Environment
- OS Version: Lubuntu 18.04x84
- Game Version: 22112816

### Detailed description of bug
**Map** Fallstation in local host
**Roles played** HOP

bug in the video
**https://youtu.be/yoY9IJQdsDI**
As explained earlier

I started the game with exactly the same profiles as the last game, for example **in 2212212** and the satchel was there  
![2022-11-29-153537_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/204559983-b9510e22-e102-4335-a078-3e77c0ac509e.png)

### Steps to reproduce

1. start the game has hop with a satchel in you preference

**Comment by MaxIsJoe** [comment] 2022-11-29 09:48
That's the satchel bag.

This is not a bug.

**Comment by corp-0** [comment] 2022-11-29 14:31
please follow the bug template to report bugs

**Comment by corp-0** [comment] 2022-11-29 14:32
other than that, I think this issue is just us wrongly setting the backpack in the satchel field for HOP occupation. @Bod9001 should know if that is the case.

**Comment by Fr-Dae** [comment] 2022-11-29 14:54
> other than that, I think this issue is just us wrongly setting the backpack in the satchel field for HOP occupation. @Bod9001 should know if that is the case.

apart from frustrating me and making me want to insult people, what's the point of replying to crap like "this is a satchel" when on the video you can CLEARLY see that it says backpack?
why answer if you don't read the description?

Why would I bother writing descriptions at all, if it's more than two words it's too complicated to read?
apparently many of the devs on your team don't know the difference between a title and a description.

the role of a beta tester is to tell if something is not working properly or could be improved / added.
not how, or at least not in detail, that's not our role. 


Again, WHY did you touch, or allow someone to touch what works, aren't there enough error reports to deal with first?
it's like the time you made a change to the hairstyle that was completely mixed up, and nobody tested it. 

If it works, don't touch it, UNLESS you have an improved version, tested by a machine AND by at least one human in a local build, and that improvement is BENEFICIAL and necessary.

**Comment by MaxIsJoe** [comment] 2022-11-29 15:12
> apart from frustrating me and making me want to insult people

I think you need to calm down.

> what's the point of replying to crap like "this is a satchel" when on the video you can CLEARLY see that it says backpack?

I'm sorry I can't see the difference between 3 pixels, but not sure why you're making a big deal out of it, since both the satchel and backpack are mechanically the same; with the dufflebag only having one more extra slot.

> Why would I bother writing descriptions at all, if it's more than two words it's too complicated to read?

So we can avoid scenarios like these

> apparently many of the devs on your team don't know the difference between a title and a description.

There is no "team" here, there's just contributors and maintainers. That's it.
Being hostile/annoying towards them is not a good idea.

> the role of a beta tester

We're alpha, not beta.

> is to tell if something is not working properly or could be improved / added.
not how, or at least not in detail, that's not our role.

No, when you submit an issue to our tracker in out development repository we expect you to provide as much details as possible because as contributors and maintainers we give our free time towards this project. We don't want to waste more time solving riddles because you're being lazy.

> Again, WHY did you touch, or allow someone to touch what works, aren't there enough error reports to deal with first?

We don't have file ownership, nor we operate that way because we're an open source project that rely on **contributors** to make such changes. Some contributors will mess up and that's why staging exists.

> If it works, don't touch it, UNLESS you have an improved version, tested by a machine AND by at least one human in a local build, and that improvement is BENEFICIAL and necessary.

You're not a developer nor an established long term contributor. You do not have any talking points in this project and how it should be operated, and I suggest you -in the most polite way possible- to shut your fucking mouth up and stop berating us while our hands are already full.

**Comment by corp-0** [comment] 2022-11-29 15:24
@Fr-Dae I have no idea why you are answering to me. I agreed with you.

**Comment by Fr-Dae** [comment] 2022-11-29 15:48
> We're alpha, not beta.

same, just more work to do, dev and tester.

> I'm sorry I can't see the difference between 3 pixels

**at least admit that you didn't take the time to watch the video** 

https://youtu.be/4SIPPkRwnoA
A, duffelbag , A backpack, a satchel, it's not just "3 pixel"

> We don't want to waste more time solving riddles because you're being lazy.

so learn to code better, so you don't have to re-do it, I don't have time to waste on tickets that won't be read.
Even a 4 second video is apparently too long for you. 


> I suggest you -in the most polite way possible- to shut your fucking mouth up and stop berating us while our hands are already full.

Just ... follow the guidline please, TESTING are a important step, please don't  forget it. NEVER
![1628936999185](https://user-images.githubusercontent.com/23202421/204573866-4b66ced8-acb6-4615-907e-bc34bd2c8f4a.jpeg)

https://youtu.be/4SIPPkRwnoA
----

> I have no idea why you are answering to me

![2022-11-29-162448_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/204572460-d6d46c3a-7247-49de-98f0-55081b86c8fd.png)
yes sure, i have absolue no reason why do NOT your asking to manage your team ...

**Comment by Alainx277** [comment] 2022-11-29 16:10
The responses to an issue generally correspond to the quality of the issue. This issue does not need a video, but a short text description. This saves time and removes unecessary details.

What this issue could have looked like:

<hr/>

# Satchel character preference is ignored

### Detailed description of bug

When selecting a Satchel in character preferences, you still spawn with a backpack.

### Steps to reproduce

1. Select Satchel as storage in character preferences
2. Start the round
3. Character has backpack instead of satchel

<hr/>

Jokes or jabs are generally not appreciated in issues.

**Comment by Fr-Dae** [comment] 2022-11-29 16:23
> 

the principle of a title is to draw attention to the message.
not to summarise it in a long sentence.
so yes, sometimes I try to add a humorous touch like "oh my god a dev has stolen my satchel 😱😱😱 ". 
I've seen this page issues on github so much that sometimes my brain melts a bit.

**Comment by corp-0** [comment] 2022-11-29 17:02
I renamed the issue and deleted derailed and unhelpful comments. Please keep the issues on-topic.

**Comment by corp-0** [comment] 2022-12-19 05:36
Should have been fixed by #9450. Feel free to reopen if the bug persists.

**Comment by MaxIsJoe** [comment] 2022-12-19 05:40
Not fixed. Emotes, pronouns and species identity are fixed; but satchels and skirts are still not being synced correctly on spawn.

**Comment by AtnerNT** [comment] 2023-01-07 10:38
satchels are skirts are now fixed arent they not?

**Comment by Fr-Dae** [comment] 2023-01-07 21:51
> satchels are skirts are now fixed arent they not?

seems to be fixed for the satchel of my character.

**Comment by corp-0** [comment] 2023-01-23 23:42
> but satchels and skirts are still not being synced correctly on spawn.

is it now? Can we close this one?

**Comment by Fr-Dae** [comment] 2023-01-23 23:43
work for my caracter, but i don't know for other tester if it's fiexed too or only for female_humain body

**Comment by corp-0** [comment] 2023-01-23 23:53
closing until someone else reports it

**Closed as completed by corp-0** 2023-01-23 23:53 UTC
Labels: Type: Bug
