### ISSUE TITLE
Handcuffs need a UI sprite

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2033] opened 2019-07-18 20:01 UTC
# Description
The hands should appear like this when handcuffed:
![cuffs](https://camo.githubusercontent.com/857a154700b3d14bde08e3e070c8ba10c6f9ffda/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3331323435343638343032313632303733362f3630313136343433363032333031373438322f756e6b6e6f776e2e706e67)

## Category
TODO

**Comment by chairbender** [comment] 2020-01-11 03:40
Duplicate of #2294 which I think is even already fixed

**Closed as completed by chairbender** 2020-01-11 03:40 UTC
Labels: Type: Feature, Group: UI
