### ISSUE TITLE
Spamming left-right-left-right movement keys behaviour

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1745] opened 2019-04-16 11:30 UTC
# Description
If you move left and right fast, the game seems to miss or ignore some keypresses, making you move twice on the same direction.
The idea is to stay on an area of two turfs while constantly moving

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.try to move back and forward in the same two turfs/tiles by only pressing left and right
2.Notice how the game doesnt respect your keypresses and moves you out of these two turfs

if this doesnt make much sense tell me, I'll try to explain it better

**Comment by fomalsd** [comment] 2019-04-16 12:37
Ahh, I think it's due to `MoveCooldown` in PlayerSync.Client that filters out move requests that happen faster than a decisecond. Was designed to avoid spamming server with move requests

**Comment by coolcat1711** [comment] 2019-07-28 23:11
> 
> 
> Ahh, I think it's due to `MoveCooldown` in PlayerSync.Client that filters out move requests that happen faster than a decisecond. Was designed to avoid spamming server with move requests

My gut response would be to implement a small move queue and update the server when off cooldown. The only problem would be if it would make movement feel artificially unresponsive if you filled the queue with too many 'In advance' commands.

**Comment by chairbender** [comment] 2019-07-28 23:22
I like the queue idea, I think it's a common practice to allow "buffering" a single move in many games. I think that would make sense here - just allow them to buffer a single move.

**Comment by chairbender** [comment] 2020-01-11 05:33
not a good first issue because movement is involved

**Comment by daalta** [comment] 2020-02-15 21:32
A movement buffer could definitely make sense, but I would clarify this to make clear *how* it's a bug. (Because I wasn't sure at first)

1. The player presses `D` and their character starts moving to the right.
2. Shortly before the the character stops moving the player presses `W`. 
3. The character finishes their movement to the right.
4. The character does not move left - the `D` input was dropped.

Instead, what should have happened:

4. The characters moves to the left because `D` was pressed within the last x milliseconds.

===

Also, here's how I would not consider a bug: When spamming.

1. The player presses `A`.
2. The character starts moving to the right.
3. The player presses `D`.
4. The player presses `A`.
5. The player presses `D`.
6. The player presses `A`.
8. The characters stops moving.
9. The player presses `D`.
10. The character moves to the right.

Even though the player was spamming `D` and `A` they moved to the right twice. This is because it was the most recently pressed movement key. Even if we added a buffer this would not be fixed, unless the player paces their `D` and `A` presses perfectly.

**Comment by MaxIsJoe** [comment] 2024-06-15 18:24
This is no longer an issue.

**Closed as completed by MaxIsJoe** 2024-06-15 18:24 UTC
Labels: Type: Bug, Priority: Low
