### ISSUE TITLE
Duplication of air scrubber/missing description

### ISSUE THREAD

**Issue by ARabidDingo** [unitystation/unitystation#5931] opened 2021-02-02 09:59 UTC
### Environment
- Game Version: 21020200
- OS Version: Windows 10 Home v1909

### Detailed description of bug
Air scrubber fittings duplicate.

### Steps to reproduce
1. Use wrench or CE drill to unbolt a scrubber fitting
2. Use wrench/drill on fitting again to attempt to reattach
3. An attached fitting appears without removing the part, duplicating it.
There is also no progress bar or action description to indicate what is happening. The disassembly sound does however play.

**Comment by ThatDan123** [comment] 2021-02-07 15:08
Cant reproduce on latest so closing

**Closed as completed by ThatDan123** 2021-02-07 15:08 UTC
Labels: Type: Bug
