### ISSUE TITLE
hair appears even with a hat/helmet

### ISSUE THREAD

**Issue by techpriest154** [unitystation/unitystation#6711] opened 2021-06-05 13:41 UTC
### Environment
- Game Version: 21060314
- OS Version: windows 10, latest

### Detailed description of bug

the hair sprite not removed if you wear a hat/helmet, this is confirmed to happen on all hair i have tested (business, afro, bun) and on all hats i have worn (too many to name)

![image](https://user-images.githubusercontent.com/78688207/120893601-07efdf00-c60c-11eb-84d2-19f270e1f04b.png)
![image](https://user-images.githubusercontent.com/78688207/120893823-1d193d80-c60d-11eb-88af-5582a67d00c3.png)
![image](https://user-images.githubusercontent.com/78688207/120893859-3fab5680-c60d-11eb-9a92-88dbd84a034c.png)

### Steps to reproduce

1. just join staging and put on a hat

**Comment by Fogapod** [comment] 2021-06-06 15:31
Seems like this also happens with felinid ears and tail

**Comment by PerfectTangent** [comment] 2021-07-17 08:30
duplicate of #4473.

**Closed as completed by PerfectTangent** 2021-07-17 08:30 UTC
Labels: Type: Bug, Group: Spriting, ValidForContest
