### ISSUE TITLE
Space wind can glitch items back and forth Making a meat grinder that Instantly kills

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3043] opened 2020-02-11 09:36 UTC
Stuff like doors to different pressurised rooms, the items next seem to glitch out going back and forth, fixing this is very much needed since it kills a lot of people unnecessarily

**Comment by daalta** [comment] 2020-02-11 13:49
Is this a duplicate of https://github.com/unitystation/unitystation/issues/2994 ?

**Comment by fomalsd** [comment] 2020-02-11 13:50
yep

**Closed as completed by fomalsd** 2020-02-11 13:50 UTC
Labels: Type: Bug
