### ISSUE TITLE
Hovering over doors after they open still show a green overlay door

### ISSUE THREAD

**Issue by Coolsurf6** [unitystation/unitystation#2910] opened 2020-02-06 05:55 UTC
**Description:**
Opening a door while hovering over it keeps a weird green overlay instead of updating while the door graphic opens. 

The graphic should either update while the door opens or make it a feature but have the overlay a lot more transparent making it possible for players to close doors behind them faster if they keep their cursor over it.

![X6GMOf9S1i](https://user-images.githubusercontent.com/16472329/73909599-cc9aae80-48f8-11ea-803d-d3b8c4fe103f.gif)

**Comment by fomalsd** [comment] 2020-02-06 06:35
Duplicate of #2873

**Closed as completed by fomalsd** 2020-02-06 06:35 UTC
