### ISSUE TITLE
Cloth inventory icons can be wrong on weaker PCs in built clients

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1998] opened 2019-07-04 11:14 UTC
# Description
![img](https://user-images.githubusercontent.com/10403536/60662414-d84a6200-9e4b-11e9-8836-d84e5e2dbe7b.png)
See picture.
They get fixed when clicking them though

## Detailed Bug Report
Introduced by changes in #1959. Delays were "fixing" icons, but player stood naked for 0.2s

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Make sure you're doing this on not very fast computer ( [Geekbench 4 CPU score](https://browser.geekbench.com/v4/cpu/search) <= 13000 ). 
The weaker the computer, the higher chance of reproduction you'll get
2. Host from editor, join from build
3. Pick a job
4. As client, expand equipment slots. Check if any of the slots show items that aren't supposed to be there (like, mime's mask instead of bartender's shoes, etc)

**Comment by chairbender** [comment] 2019-09-03 02:24
probably can also reproduce easier just by removing the hardcoded WaitForSeconds to make this problem more apparent. WaitFor is a band aid fix to init issues that need to be fixed by guaranteeing init happens properly regardless of startup times.

**Comment by chairbender** [comment] 2019-11-11 01:48
This might be fixed as of #2245 , slots are supposed to be a lot more reliable about displaying the correct sprites, but needs to be confirmed this is fixed.

**Comment by chairbender** [comment] 2020-01-14 03:25
I'm going to assume this is fixed since we don't use unicloths anymore and haven't seen it happen.

**Closed as completed by chairbender** 2020-01-14 03:25 UTC
Labels: Type: Bug, System: Animation
