### ISSUE TITLE
Blood on the floor block construction

### ISSUE THREAD

**Issue by ReiderJack** [unitystation/unitystation#3374] opened 2020-02-27 05:16 UTC
![BloodBlockConstruction](https://user-images.githubusercontent.com/42844726/75414378-6c1bf180-5939-11ea-92d7-67d47dc4ea95.gif)

**Comment by ReiderJack** [comment] 2020-02-27 14:21
![InTheway](https://user-images.githubusercontent.com/42844726/75453786-7bc12780-5985-11ea-8e47-789e251cdd27.gif)

**Comment by drneuris** [comment] 2020-02-27 16:12
servervalidations.IsConstructionBlocked() checks for gameobjects' layer skipping floor and wallmount layers, but all decal prefabs have layer set to default so maybe that's why they'll block constructions

could be an easy fix but i'd ask more knowledgeable people about the best course

**Comment by daalta** [comment] 2020-02-29 15:21
Duplicate of https://github.com/unitystation/unitystation/issues/2984 ... But these gifs are excellent. Thank you for reporting this @ReiderJack !

**Closed as completed by daalta** 2020-02-29 15:21 UTC
