### ISSUE TITLE
Reactor creates infinite destruction zone

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6772] opened 2021-06-08 18:17 UTC
Linux- staging

containing the reactor's blast in magic walls, admin-spawned
creates an area that immediately destroys anything that enters that tile
![Screenshot at 2021-06-08 14-07-00](https://user-images.githubusercontent.com/55299415/121236619-2819db00-c864-11eb-8e6e-83e8d722f042.png)

https://user-images.githubusercontent.com/55299415/121236652-30721600-c864-11eb-868a-31d14a0da737.mov

**Comment by Bod9001** [comment] 2021-06-11 20:30
wasn't able to replicate an editor, with magic walls I suspect has something to do with nan values that have been seeing from reactor explosions

**Comment by Pockets-byte** [comment] 2021-06-11 21:35
I've honestly discovered that putting reactors in an indestructible box
causes a lot of weird and inconsistent behavior

**Comment by corp-0** [comment] 2021-06-12 01:18
> wasn't able to replicate an editor, with magic walls I suspect has something to do with nan values that have been seeing from reactor explosions

it does happen in staging tho

**Comment by jamessimo** [comment] 2021-06-13 11:19
I just want to mention that it’s also common on staging that people caught anywhere near a reactor when it blows up causes their brute damage to display and NaN on all limbs and leaves the player unable to move. The player doesn’t die and doesn’t go into crit.

**Comment by Aranclanos** [comment] 2021-06-22 18:30
couldn't reproduce on editor or headless

**Comment by Aranclanos** [comment] 2021-06-22 19:09
Alright I did a bit more investigation based on logs and code and I believe this was fixed by #6625

the 8th of this month there were people talking in OOC about magic walls stopping explosions, so I went into explosion code and found nothing related to it, but I guessed that a runtime would cause the explosion to fully stop and re-start at the previous point it was.

https://discord.com/channels/273774715741667329/730869781040726071/851884634870120528
```InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <fb001e01371b4adca20013e0ac763896>:0)
HealthV2.RootBodyPartContainer.TakeDamage (UnityEngine.GameObject damagedBy, System.Single damage, AttackType attackType, DamageType damageType, System.Single armorPenetration, System.Boolean damageSplit) (at /root/UnityProject/Assets/Scripts/HealthV2/Living/BodyParts/RootBodyPartContainer.cs:342)
HealthV2.LivingHealthMasterBase.ApplyDamageAll (UnityEngine.GameObject damagedBy, System.Single damage, AttackType attackType, DamageType damageType, System.Boolean damageSplit) (at /root/UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs:583)
Systems.Explosions.ExplosionNode.Process () (at /root/UnityProject/Assets/Scripts/Systems/Explosions/ExplosionNode.cs:71)
Systems.Explosions.ExplosionManager.Step () (at /root/UnityProject/Assets/Scripts/Systems/Explosions/ExplosionManager.cs:40)
UpdateManager.ProcessDelayUpdate () (at /root/UnityProject/Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:298)
UpdateManager.Update () (at /root/UnityProject/Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:278)
```

this error was happening at the same time

the PR I mentioned fixed this bug 2 days before but the server wasn't updated at that point yet

**Comment by Pockets-byte** [comment] 2021-06-22 19:10
I can try testing this now.

**Comment by Pockets-byte** [comment] 2021-06-22 19:18
additional testing is needed. but now the full magic wall encirclement doesn't block it at all 
![Screenshot at 2021-06-22 15-14-02](https://user-images.githubusercontent.com/55299415/122986092-f5480a80-d36c-11eb-951f-793b131b3dcc.png)
this is fairly similar to me discovering that things that aren't tiles. like wizard-casted magic walls. or doors, don't block reactor explosions at all

**Comment by Aranclanos** [comment] 2021-06-22 19:22
its just runtimes stopping explosioins from growing, I'll change it so once a runtime happens it doesn't get stuck in a loop where it always explodes the same area

the magic walls were unrelated and just a coincidence

**Closed as completed** 2021-06-22 23:26 UTC
Labels: Type: Bug, Priority: High, ValidForContest
