### ISSUE TITLE
Map Blast Detectors

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#9052] opened 2022-08-05 14:01 UTC
Map Blast Detectors in main stations

- [ ] Boxstation
- [ ] Outpoststation
- [ ] fallstation
- [x] Squarestation
- [ ] Unrealstation

**Comment by AtnerNT** [comment] 2022-11-25 08:17
#9377 Maps blast yield detectors to mini

**Comment by corp-0** [comment] 2023-03-06 15:54
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

If any station is missing the blast detectors, please open an issue per station.

**Closed as completed by corp-0** 2023-03-06 15:54 UTC
Labels: Type: Feature, Bounty Candidate, Group: Mapping
