### ISSUE TITLE
UniCloth doesn't work

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2216] opened 2019-10-21 15:06 UTC
# Description
![img](https://user-images.githubusercontent.com/10403536/67216238-61dd6a00-f412-11e9-84c6-abbde3fa107d.png)
Should UniCloth be removed? Since we apparently use prefab-per-cloth now?

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Go to mining
2. Open mining closet
3. See questionmark clothes

**Comment by chairbender** [comment] 2019-11-06 04:56
We still have the same uni prefabs as before, not prefab per cloth.

The issue with those is most likely how they are mapped or spawned in.

I think the new inventory system could be used to set initial locker contents once it's merged.

**Comment by chairbender** [comment] 2019-11-11 01:40
Actually from what I see, the issue is that the mining hardsuit is mapped on top of the locker but it is not initializing properly or something is wrong with how it is mapped. It's not defined as part of the locker's starting items. I think this particular issue can be resolved by ensuring the tilemap entry for mining hardsuit / helmet is set up correctly and remapping these.

Regardless, just want to call out that #2255 would allow you to define their default contents to include cloths so they wouldn't need to be manually mapped.

**Comment by chairbender** [comment] 2019-11-11 01:41
these suits / helmets absolutely need to be mapped for release so miners can actually do something

**Comment by Bod9001** [comment] 2019-11-20 01:14
mining stuff is Because they are missing references, Simple as

**Comment by chairbender** [comment] 2019-11-20 01:34
yup, this will be fixed in the pr

**Closed as completed** 2019-11-22 05:59 UTC
Labels: Type: Bug
