### ISSUE TITLE
Plasma inhalation toxin damage needs to be reimplemented

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7483] opened 2021-09-28 16:30 UTC
### Environment
- Game Version: Staging Latest
- OS Version: Arch linux

### Detailed description of bug

as the title says plasma gas doesn't cause lung damage anymore
example:

https://user-images.githubusercontent.com/80334192/135127331-bf6bbb33-6d62-475c-b0c8-8d2953b66a36.mp4

### Steps to reproduce

1. breathe in a plasma gas filled room

**Comment by PerfectTangent** [comment] 2021-09-28 21:59
technically a duplicate of the plasma gas point in #6195. It's not broken. Plasma gas and gas masks need to be reimplemented into the new health and lung system.

**Closed as completed** 2021-10-17 02:34 UTC
Labels: Type: Refactor, System: Atmos, System: Damage
