### ISSUE TITLE
Brute Packs deal damage instead of healing it under certain circumstances

### ISSUE THREAD

**Issue by VernaSaurus** [unitystation/unitystation#6127] opened 2021-02-26 07:38 UTC
When attempting to heal oneself with brute packs, if you have taken damage in multiple limbs or body parts, you will instead harm yourself upon use. However, testing has shown that with only two damaged limbs, the brute pack will instead refuse to heal damage. Notably, only the third onward body parts will take damage from using a brute pack. I do not currently know if this also affects burn damage, but will update this report after testing. Donuts, when consumed by security personnel, do still properly heal under all circumstances.

NOTE: It is currently unknown if this is a LOCAL ONLY bug, as I have not yet personally encountered it on production or staging **that I can recall.**

**Comment by PerfectTangent** [comment] 2021-03-09 04:03
needs testing now that we have merged health

**Comment by Aranclanos** [comment] 2021-05-06 20:36
Can't reproduce

**Closed as completed** 2021-05-15 10:41 UTC
Labels: Type: Bug, Status: Needs Reproduction, System: Damage, System: Health
