### ISSUE TITLE
Attacking lockers, closets and crates with melee isn't working.

### ISSUE THREAD

**Issue by SimplySmiley** [unitystation/unitystation#5574] opened 2020-11-09 11:12 UTC
- Game Version: _5538 ; 4116_
- OS Version: _Windows 10_

- Description of the bug:
_Player is unable to attack any lockers, closets and crates with any melee weapons while it's supposed to be possible to do._

- Tested on: _Security lockers; common closets (welded); Captain's locker; secure engineering crate_
- Tested with: _fists; crowbars; toolboxes; batons; null rod_

**Comment by jamessimo** [comment] 2020-12-11 07:16
Seems like a duplicate of #5313 

Recommend merging this issue.

**Comment by PerfectTangent** [comment] 2021-04-26 01:07
Agreed, it does look like a duplicate. Closing in favour of #5313.

**Closed as completed by PerfectTangent** 2021-04-26 01:07 UTC
Labels: Type: Bug
