### ISSUE TITLE
[BUG] The PDA does not show names on the crew manifest list

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9442] opened 2022-12-15 06:22 UTC
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22121502

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

![image](https://user-images.githubusercontent.com/34368774/207786383-3231fa88-d81e-4c16-8569-b955770f4cbf.png)

Names aren't appearing in the crew manifest on the PDA

### What should have happened instead?

Names should be shown next to titles

### Steps to reproduce the issue

1. Use your PDA
2. Check crew manifest 
3. See names not shown

**Comment by AtnerNT** [comment] 2024-06-12 12:54
Duplicate of #9963 which was fixed in #9972

**Closed as completed** 2024-06-17 23:04 UTC
Labels: Type: Bug
