### ISSUE TITLE
Feature: Headsets B: 50

### ISSUE THREAD

**Issue by Em3rgencyLT** [unitystation/unitystation#505] opened 2017-12-03 11:10 UTC
# Preliminary information

## Category
Feature

# Description

- When entering chat, the user should be able to select a channel they will speak in. There should be a small icon displaying the current channel in front of the text input. Clicking the icon will list the icons of other possible channels.
- The chat box should remember the previous channel when entering it to type a new message
- Channels always available for everyone: 
![image](https://user-images.githubusercontent.com/15195221/33524741-0cf3ae50-d82b-11e7-8b72-cc1865441016.png) 
![image](https://user-images.githubusercontent.com/15195221/33524745-1742442a-d82b-11e7-92f7-33a860df04d1.png)
- Channels available to everyone with a headset: 
![image](https://user-images.githubusercontent.com/15195221/33524753-34e2011e-d82b-11e7-98b7-e8100013eb03.png)
- Channels available based on encryption key in headset: 
![image](https://user-images.githubusercontent.com/15195221/33524762-4fd4954a-d82b-11e7-8bcd-810258da6802.png)
- Headset encryption keys can be removed with a screwdriver and replaced with other encryption keys
- A headset without an encryption can only send messages to 
![image](https://user-images.githubusercontent.com/15195221/33524755-36e1ae1a-d82b-11e7-9fee-7b0a67a5f8e4.png)
- A single key can give access to more than one channel. For example the captains headset encryption key might give access to all channels.

**Comment by fomalsd** [comment] 2017-12-03 22:04
If you're updating chat system, I **highly** suggest moving it onto our network message system, it's a perfect candidate for that!
Client should be able to send a **client** ChatSendRequestMessage to server with:
-Message text (will be modified on server if a person's drunk etc.)
-Channel that he wishes to write to (his actual ability to speak in this channel will be validated on server)

Then in the Process() method server will have to check if player wears a headset that allows him to chat in the channel. If not (client tampering), it won't go any further.
Also a check if player is dead -> no local chat for him
Then there should be a check for sender's condition flags, like stuttering and being drunk, and applied to message text.

After that the prepared **server** ChatMessage should be sent _only_ to the corresponding players that are allowed to receive messages of this channel (we should think about storing some lists serverside).
ChatMessage should have:
-Final message text with all modifications and sender's name
-Channel info
In the Process() method client will just print whatever was received into the chat window, colored according to the channel name.

In the future local channel should use proximity (when that will be a thing).

That's a good opportunity to learn how netmessages work (and how easy it is to make them work as intended)

**Comment by DooblyNoobly** [comment] 2017-12-03 22:44
Yea I agree. We really need a wiki on how to construct messages, it seems complicated at first but when you do it once you see how easy it is

**Comment by Em3rgencyLT** [comment] 2017-12-04 06:28
Thank you for the suggestions @fomalsd. It's almost exactly how I'm trying to implement it. In addition to general code cleanup.

 I've redone the message struct into its own class. Besides having message and timestamp it also stores the string of speaker name, channel enums and the modifier enums (drunk, clown, etc). That same class handles all the required cleanup and editing of the messages. Now it's just a matter of having the server instantiate them correctly based on the player and modifying the UI to display them correctly (color). Color information will be client side to allow for personal settings, if we ever want to do that.

**Comment by fomalsd** [comment] 2017-12-04 07:14
I really think that actual modifiers should be determined by server, otherwise modified client would allow people to always chat normally (i.e. even if they are monkeys)

**Comment by Em3rgencyLT** [comment] 2017-12-04 07:25
Well they can be determined by server!

If you want to add a message to the queue right now, all you do is
`new ChatEvent(args);`
Just by creating this object, it will modify the message on its own, based on the arguments you provided. You literally don't have to worry about it. And those arguments can be determined server side.

Everything in the ChatEvent class is neatly commented and very self explanatory so it can both easily be extended and modified if necessary.

Now regarding monkeys... "foreign" languages are a bit out of scope for the current headset feature. It can't be a modifier, because if two monkeys are talking they still need to see the original text. I think adding a "language" enum as part of the ChatEvent constructor and a static function to obfuscate the language would solve this issue.

```
if(player.canSpeak(languageEnum.language)) {
     displayOriginalMessage();
} else {
   //Turns the message into appropriate length "Oook eeek eekk!" in case of monkey
    ChatEvent.Obfuscate(languageEnum.language, message.Length());
}
```

**Comment by DooblyNoobly** [comment] 2017-12-06 09:03
Criteria:

 - Complete the feature

Bounty: 50 usd paid via paypal on successful merge

**Closed as completed** 2017-12-09 01:05 UTC
Labels: Bounty
