### ISSUE TITLE
Holding an item doesn't allow you to switch to the respective hand with the mouse cursor.

### ISSUE THREAD

**Issue by RealPlanet** [unitystation/unitystation#2724] opened 2020-01-24 09:34 UTC
If you are holding an item the only option is to use the keybind to switch hands, you cannot simply click on the ui hand to switch to it.

**Comment by JesterX666** [comment] 2020-02-08 02:06
Was not reproduced

**Comment by RealPlanet** [comment] 2020-02-08 09:19
> Was not reproduced

If you have an empty hand and you click to switch on a hand that holds an item, the item will switch hands if you have both hands full nothing will happen. In both cases it's not behaving as expected.

**Comment by PerfectTangent** [comment] 2021-05-15 10:13
Could not reproduce, and changes to the hand UI has made it easier to switch hands, because you can click the rim of the hand slots. Closing.

**Closed as completed by PerfectTangent** 2021-05-15 10:13 UTC
Labels: Type: Bug, Status: Needs Reproduction, Group: UI
