### ISSUE TITLE
Objects are "teleporting" while being pulled

### ISSUE THREAD

**Issue by ilinm1** [unitystation/unitystation#8563] opened 2022-04-12 19:45 UTC
### Environment
- Game Version: latest staging at the moment
- OS Version: 

### Detailed description of bug

https://user-images.githubusercontent.com/57045293/163041304-4fee4930-9086-4bad-8b3c-72e1bafc3c57.mp4

Like that.

### Steps to reproduce
Appears while transitioning between matrices, sometimes in lavaland.

**Comment by MaxIsJoe** [comment] 2022-04-13 10:46
duplicate of #8357

**Closed as completed** 2022-04-13 15:34 UTC
Labels: Type: Bug
