### ISSUE TITLE
Cargo Selling Needs to Account for Items That Hold Items B: 25

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2400] opened 2019-11-30 20:18 UTC
# Description

Current cargo system does not account for items that hold other items, such as crates. Ensure that the prices are updated correctly, and the export scanner says it includes contents (search for TODO with this id).

**Comment by chairbender** [comment] 2019-12-01 02:06
You can find the contents of the object like so. Crates and lockers both use ClosetControl to allow storing contents.

First, add a way to get contents to ClosetControl. I don't know if contents is synced to clients, so prefix with server to be safe:
```csharp
// add this to ClosetControl
public IEnumerable<ObjectBehavior> ServerHeldItems
{
  get
  {
    return heldItems;
  }
}

```

Now how to get them
```csharp
var closetControl = someObject.GetComponent<ClosetControl>();
if (closetControl != null)
{
  IEnumerable<ObjectBehaviour> heldItems = closetControl.ServerHeldItems;
  //see if they have prices, etc...
}
```

**Comment by StrawberryMoses** [comment] 2019-12-01 02:30
Do lockers and crates use itemStorage? I was thinking we could just check for that instead, and have it apply for things like backpacks and boxes as well

**Comment by chairbender** [comment] 2019-12-01 02:36
They don't currently. I considered it but decided not to implement that change because of the complication that lockers can hold things like players / mobs. I am not opposed to allowing them to use item storage for their held items but special care would need to be taken concerning that issue, so you would still end up with some custom logic specific to closets if you leave a monkey in a locker on the shuttle for example.

In the above logic you would also need to check if the items had ItemStorage as well, forgot about that.

**Comment by StrawberryMoses** [comment] 2019-12-01 02:37
Ah, that makes sense to me then. Don't see any shame in handling both

**Comment by DooblyNoobly** [comment] 2019-12-04 08:55
Contributor will receive a bounty of 25usd on a successful merge of a solution that resolves the issue above.

**Comment by StrawberryMoses** [comment] 2019-12-04 22:30
I'll take care of this one

**Comment by fomalsd** [comment] 2019-12-08 16:32
There's still a bug with wrong count of items inside crates, so it's not yet finished

**Comment by chairbender** [comment] 2019-12-13 15:30
@StrawberryMoses planning to fix this?

**Comment by StrawberryMoses** [comment] 2019-12-18 01:03
@fomalsd Do you remember how to trigger this? In editor, I can put a few wrenches and welding tools in different containers (including crates), and nothing seems to be amiss

**Comment by fomalsd** [comment] 2019-12-18 07:22
spawn 4 or more extinguishers (remember how many), place them into a crate. sell it and see how many will be listed as sold in cargo console. I think it was 2x of real number for me

**Comment by StrawberryMoses** [comment] 2020-01-06 00:46
Holidays finally over- taking a look at this, I put 5x fire extinguishers in a crate, and it showed the correct amount. I also tried a few in multiple crates but nothing. Maybe close this one and assign it to me again if there's a reproduce?

**Comment by chairbender** [comment] 2020-01-06 01:35
sounds good, I'll validate

**Comment by chairbender** [comment] 2020-01-06 03:49
I am still able to reproduce. I put 4 crates on the shuttle, each with 2 fire extinguishers, in multiple ways. It told me I sold 14 extinguishers.
Here are the 4 different ways I put them on:

1. Spawn crate on cargo shuttle, spawn 2 extinguishers on shuttle, put in crate.
2. Spawn crate on cargo shuttle, spawn 2 extinguishers in station, carry them in inventory over to cargo shuttle and put them in the crate.
3. Spawn crate and extinguishers in station, put them in the crate, drag crate over to cargo shuttle.
4. Spawn crate on station, drag it into cargo shuttle. Spawn extinguishers on station, carry over to cargo shuttle and put in crate.

I'll narrow it down.

EDIT: Did this as host player btw.

**Comment by chairbender** [comment] 2020-01-06 03:52
Okay, so after doing the above (same round) I just stood in the station and spawned one crate with 2 fire extinguishers and put them in the crate. Then dragged the crate into the cargo shuttle then sent it. It told me I sold 16 fire extinguishers and 5 crates.

**Comment by chairbender** [comment] 2020-01-06 04:08
I think there might be a bug in lifecycle system somehow. Just had a weird glitch where when I spawned a crate on the shuttle and 2 extinguishers and then opened the crate, the extinguishers jumped into the crate. I think the object parent / child relationship is not being cleared when they despawn.

**Comment by chairbender** [comment] 2020-01-06 04:42
I'll push a fix for this, I see the issue.

**Comment by chairbender** [comment] 2020-01-06 04:55
This should be fixed now with that above PR. I just added one extra thing to moses PR so they can have the bounty.

In order to reproduce it, it was necessary to spawn everything on the cargo shuttle itself (crate + 2 extinguishers) then put them into the crate. There seems to be an issue where objects in closets don't get put into the objects layer of the new matrix when their container crosses matrices.

I'll leave this open for now so someone else can review and close (@DooblyNoobly or @fomalsd ) to confirm

**Comment by StrawberryMoses** [comment] 2020-01-06 13:10
That's pretty weird- didn't even think to spawn stuff on the shuttle. Thanks for the fix!

As for bounty, I left this open for so long just keep it in the pool

**Closed as completed** 2020-01-09 06:29 UTC
Labels: Type: Feature, Bounty, Priority: High, System: Cargo
