### ISSUE TITLE
Completing bounties doesn't actually give cargo credits.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7550] opened 2021-10-09 04:14 UTC
### Environment
- Game Version: Staging 21100617
- OS Version: Windows 10

### Detailed description of bug

When you complete bounties, cargo doesn't actually receive funds for them. The cargo console won't even inform you if bounties have been completed when you send over requisite items. All that happens is that the relevant bounties are removed from the bounty tab.

### Steps to reproduce
1. Obtain items for one of the default bounties and send them aboard the shuttle.
2. Notice that you have not received funds for the bounty, only for the items themselves.
3. Check the bounty tab, the bounty whose items you sent over is now gone.

**Comment by MaxIsJoe** [comment] 2021-10-19 00:59
Having trouble re-creating this issue along side #7548 , can you provide more info about how you managed to find this issue and what were the circumstances around it?

**Comment by Ahion** [comment] 2021-10-19 05:28
I tried repeating this. Credits are accrued correctly.  I think the problem is that there is no message about the completion of the bounty.

**Comment by PetMudstone** [comment] 2021-10-19 05:33
I can confirm this after repeated testing. Credits are paid but you are not informed of bounty completion.

**Comment by PerfectTangent** [comment] 2021-10-19 08:17
alright, closing then, as that's covered in #6150.

**Closed as completed by PerfectTangent** 2021-10-19 08:17 UTC
Labels: Type: Bug, System: Cargo
