### ISSUE TITLE
Weird oxygen behavior and "gasp" text broken.

### ISSUE THREAD

**Issue by badbon** [unitystation/unitystation#1598] opened 2019-03-02 16:45 UTC
# Description
Oxygen behaves very strangely in general. Sorry if I am missing something since I haven't looked into unitystation in a while, but. 

* Turning on oxygen supply doesn't seem to do anything.
* "Gasp" text is broken, it doesn't stop whenever it gets triggered (see video below)

## Category
BUG

## Detailed Bug Report
Video describing the specific scenario I mentioned (P.S, doesn't matter if I turn on oxygen off or on, same results) https://www.dropbox.com/s/q6hdtn5tbpbqitt/FXStvT2GO2.mp4?dl=0

## Steps to Reproduce
Spawn as syndie, turn on oxygen (or not, no difference) go out in space. 

You also get randomly thrown into crit when in space for too long which seems pretty unintuitive to me.

**Comment by Fishfish458** [comment] 2019-03-02 19:44
as well, In multiplayer I've noticed that clients that are suffocating causes the host to gasp
![gasping](https://user-images.githubusercontent.com/47410468/53686779-44c42180-3cf1-11e9-88df-58f848980266.png)

**Comment by fomalsd** [comment] 2019-03-02 22:26
> Turning on oxygen supply doesn't seem to do anything.

Did you see this? Oxygen tank only works in this slot currently:
<img width="314" alt="scr 2019-03-03 1 25 01" src="https://user-images.githubusercontent.com/10403536/53688315-48889000-3d53-11e9-9f95-94274bd8c946.png">

**Comment by fomalsd** [comment] 2019-03-02 22:29
And yeah, gasping chat message is called for serverplayer instead of one who's supposed to suffer

**Comment by krille90** [comment] 2019-03-02 22:45
> "Gasp" text is broken, it doesn't stop whenever it gets triggered (see video below)

I dont think the gasping is a bug. From the video I would say that you were venting the syndie ship, so there isn't enough pressure left and the player starts to gasp.

**Comment by badbon** [comment] 2019-03-03 06:05
> > "Gasp" text is broken, it doesn't stop whenever it gets triggered (see video below)
> 
> I dont think the gasping is a bug. From the video I would say that you were venting the syndie ship, so there isn't enough pressure left and the player starts to gasp.

Hm, I think it never stops though? haven't tested that properly. Will syndie ship get depressurized that fast? dunno.

**Comment by badbon** [comment] 2019-03-03 06:08
> > Turning on oxygen supply doesn't seem to do anything.
> 
> Did you see this? Oxygen tank only works in this slot currently:
> <img alt="scr 2019-03-03 1 25 01" width="314" src="https://user-images.githubusercontent.com/10403536/53688315-48889000-3d53-11e9-9f95-94274bd8c946.png">

I don't think I picked anything other than default syndie gear.

I assumed oxygen tanks were unimplemented because I managed to get oxygen display to toggle to "on".

**Comment by krille90** [comment] 2019-03-12 20:42
>  I managed to get oxygen display to toggle to "on".

Yea, that shouldn't happen

**Comment by fomalsd** [comment] 2019-03-20 09:51
could someone please check if this was fixed by #1648?

**Comment by DooblyNoobly** [comment] 2019-03-20 09:52
I was getting Gasp text but it wasn't coming from my player

**Comment by HydraulicSheep** [comment] 2019-04-12 03:36
I'll take a look at this.

**Comment by HydraulicSheep** [comment] 2019-04-12 13:46
Ok so I've fixed the broken gasp text with my latest [commit](https://github.com/HydraulicSheep/unitystation/commit/7d2ebd48fa68f3b7921b3645499820b907529eea)
I'm still working on the oxygen behaviour issues

**Comment by HydraulicSheep** [comment] 2019-04-12 13:48
The text now reads "{Player} gasps" and only shows for nearby players

**Comment by fomalsd** [comment] 2019-04-12 13:52
@HydraulicSheep try checking it with animals (vent a room with Pete for example), I think it might give you an NRE because animals don't have playerScript

**Comment by HydraulicSheep** [comment] 2019-04-12 14:46
This now works for both humans and non-humans.
![Petegasps](https://user-images.githubusercontent.com/24516366/56045913-7ff05080-5d85-11e9-8439-2483a9b0415e.png)

**Comment by HydraulicSheep** [comment] 2019-04-12 14:47
There is also definitely an issue where you continue taking damage from oxygen-loss even after you have returned to a safe environment. Is this intended?

**Comment by Fishfish458** [comment] 2019-04-12 14:54
right now, rooms vent super fast, it might be that you're still in an oxygen-less room.

**Comment by HydraulicSheep** [comment] 2019-04-13 05:48
Yeah thanks @Fishfish458 I've double-checked and I can't reproduce any other suspicious oxygen behaviour. I think any other issues were fixed in https://github.com/unitystation/unitystation/pull/1648

**Comment by HydraulicSheep** [comment] 2019-04-13 05:49
I'm opening a PR

**Closed as completed** 2019-04-13 23:15 UTC
Labels: Type: Bug
