### ISSUE TITLE
Walking dead

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2746] opened 2020-01-26 02:13 UTC
## Description

Some situations can cause dead players to appear standing. It's not clear what the circumstances are. The only reason they should be standing is if they are buckled to chairs, and they should lay down when unbuckled. Other than that, it needs to be ensured that all dead players always appear down.

**Comment by chairbender** [comment] 2020-01-26 02:14
Not putting this in 0.4 because it's not a huge impediment IMO. But feel free to fix if inspired or you see an easy way to fix.

**Comment by fomalsd** [comment] 2020-01-26 13:13
Duplicate of #2407

**Closed as completed by fomalsd** 2020-01-26 13:13 UTC
Labels: Type: Bug, Affects only: Headless
