### ISSUE TITLE
Unity Editor Crash Bug B: 90

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1497] opened 2019-02-05 00:28 UTC
# Description

## Category
BUG or TODO?
BUG
## Detailed Bug Report
I got the files from github and tried to open them with unity. Unity did not find the lobby executable. So I went into the folder and found it, and closed unity, then I launched it. It turned on unity but did nothing, so I closed Unity and executed it again. It was loading all the files and when it was done loading, it crashed.
## Steps to Reproduce

Please enter the steps to reproduce the bug or behaviour:
1. Load lobby scene
2. Press play in the editor
3. Crash

[Editor.log](https://github.com/unitystation/unitystation/files/2830288/Editor.log)
[error.log](https://github.com/unitystation/unitystation/files/2830289/error.log)

**Comment by DooblyNoobly** [comment] 2019-02-12 22:44
I'm putting a large bounty on this one as it will take some time to figure out. Contributor will be rewarded with 90 usd on the successful merge of a solution.

I recommend first removing the SunVox library to see if that is the cause. Generally the best approach to an intermittent problem like this is to disable sections of the code until the bug goes away then you can narrow down where the problem is easier. I'd also recommend focusing on the editor tools and scripts as they might be the culprit too.

**Comment by Itsnotjames** [comment] 2019-02-13 06:10
I had this issue until I restarted my computer. Now it works without any errors or crashes with no differences from the current branch.
I think this is a client-side issue and not with the project.

**Comment by DooblyNoobly** [comment] 2019-02-13 08:28
I just removed all libs from plugins (sunvox, facepunch, WebSocketSharp) and the crash is still there. I'm thinking we look at Atmos thread next.

**Comment by Jibbajabbafic** [comment] 2019-02-13 09:04
The editor you use doesn't affect it either. It could be specific to Win10 though, foma doesn't experience it with his Mac

**Comment by Bod9001** [comment] 2019-02-14 11:26
Maybe it's one of the 600+ warnings?

**Comment by fomalsd** [comment] 2019-02-15 12:59
I think it's been fixed in #1553

**Comment by DooblyNoobly** [comment] 2019-02-17 05:20
Seems like the major crash bug has been fixed now. Closing

**Closed as completed by DooblyNoobly** 2019-02-17 05:20 UTC
Labels: Type: Bug, Bounty
