### ISSUE TITLE
Shuttle radar is broken, no station/other shuttle display icons

### ISSUE THREAD

**Issue by badbon** [unitystation/unitystation#2068] opened 2019-07-29 07:27 UTC
# Description
Same as title. there used to be icons for each shuttle and the station itself, theyre not being shown now.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pick syndicate team
2. Go into shuttle console
3. ??? profit

**Comment by fomalsd** [comment] 2019-08-09 13:33
Duplicate of #2066

**Closed as completed by fomalsd** 2019-08-09 13:33 UTC
Labels: Type: Bug
