### ISSUE TITLE
After some time, unable to throw objects then unable to click entirely.

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#2964] opened 2020-02-08 12:41 UTC
After around an hour and a half of playing on one server, the player is unable to throw objects (I use the 'R' keybind so that may be it) with the throw option, grenades still function fine. After about 2-3 hours of play on one server without disconnecting the player is unable to click on objects entirely.

**Comment by NoooneyDude** [comment] 2020-09-03 07:36
I haven't seen this issue - couldn't reproduce it, or heard anyone talking about it. This was probably the result of something else failing, like one of the managers. Closing the issue.

**Closed as completed by NoooneyDude** 2020-09-03 07:36 UTC
Labels: Type: Bug, Status: Needs Reproduction
