### ISSUE TITLE
[BUG] IA Can't speak

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10477] opened 2024-08-07 09:57 UTC
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
24.08.03.21

### I was
Server (local host)

at IA

### OS
Windows 8, 10, 11

### What happened?
if you move over a person, when you write locally, the camera has the "write" icon but the message doesn't appear, 

Similarly, if someone is talking next to a camera, the ia cannot read (or hear) the message. 

### Steps to reproduce the issue

1. spawn at IA
2. speak
3. nobody can ear you

**Comment by MaxIsJoe** [comment] 2024-08-07 10:04
The AI has to choose which channels it should speak in. You don't talk through the camera.
Duplicate of #7169

**Closed as completed by MaxIsJoe** 2024-08-07 10:04 UTC
Labels: Type: Bug

**Comment by Fr-Dae** [comment] 2024-08-07 10:10
Ia can't hear locally? or read lips?

We have the technology to create black holes, but not to add microphones to cameras? 

So why does the camera have a dialogue bubble when you're writing?

**Comment by MaxIsJoe** [comment] 2024-08-07 10:27
> Ia can't hear locally? or read lips?

That is the duplicate issues that will be resolved.

> We have the technology to create black holes, but not to add microphones to cameras?

AIs never had the ability to communicate locally through cameras. That's why in SS13, they use projectors.
When AIs talk, their message gets sent through their body (aka their core) because that's where they're physically speaking. When AIs want to communicate with the rest of the station, they use comms. It's intended to be this way so when the comms go out, the AI is unable to rely info back to other players.

> So why does the camera have a dialogue bubble when you're writing?

Because the speech bubble is connected to your ghost/mind, not body.

**Comment by Fr-Dae** [comment] 2024-08-07 10:30
So you think it's normal for AI not to be able to read dialogue? (localy) 
How is this interesting from a gameplay point of view? Apart from discouraging people from playing AI?

**Comment by MaxIsJoe** [comment] 2024-08-07 10:32
> So you think it's normal for AI not to be able to read dialogue? (localy) How is this interesting from a gameplay point of view? Apart from discouraging people from playing AI?

Read what I said again.

**Comment by Fr-Dae** [comment] 2024-08-07 10:37
> on ss13 it's not like that,

 AND?
unitystation has its own independence, so why restrain yourself, 
from a gameplay point of view, I don't understand this choice.
After all, if it's because it's technically complicated to do that, then I'd understand.

**Comment by MaxIsJoe** [comment] 2024-08-07 10:47
> I don't understand this choice.

The answer to that is once again in my response:

> It's intended to be this way so when the comms go out, the AI is unable to rely info back to other players.

AI is a role about information and map control. By limiting AI in this way, antags have a chance to limit the amount of information the crew can have so they can easily set up or push whatever area they want in the station without the AI constantly informing the crew their next moves.

This is not a choice we personally made, this is quite literally what several years of countless community balancing and experimenting has led to for AI.

**Comment by Fr-Dae** [comment] 2024-08-07 11:08
Ok, 
but in what way is it incompatible with the fact that an ia, 
on the single view of a camera (i.e. locally) can hear/read the conversation of a person within the camera's range?

**Comment by Bod9001** [comment] 2024-08-07 11:25
is ss13 standard practice Have it this way

**Comment by Fr-Dae** [comment] 2024-08-07 11:29
> is ss13 standard practice Have it this way

it's a good thing we're on unitystation and not ss13, No ?

**Comment by AtnerNT** [comment] 2024-08-07 12:20
To summarise:
The AI not being able to speak through cameras is an intentional feature as it leads to gameplay that people enjoy in ss13, there is not intention currently to change that mechanic.

As for not being able to hear locally, yes that is a bug. But as Max pointed out earlier, there is already an issue reporting that bug, so this issue is closed as it is a duplicate of that ticket.

**Comment by Fr-Dae** [comment] 2024-08-07 12:34
thankq you atner
