### ISSUE TITLE
Placing an item on a table always places it to the middle of the tile

### ISSUE THREAD

**Issue by JukeJukestar** [unitystation/unitystation#7025] opened 2021-07-11 13:12 UTC
### Environment
- Game Version: Staging Build #21070919
- OS Version: Windows 10

### Detailed description of bug

On staging, putting an item on a table no longer puts it where the cursor is and instead always places it in the middle of the tile.
This is bad because you can no longer select items by clicking them and always have to use the scroll wheel. It also makes decoration impossible and your dreams of having a nicely sorted bar are shattered.

### Steps to reproduce

1. Grab a delicious can of Space Cola™
2. Place it on a table for your patrons to drink
3. Realize everything is always in the middle of the table, making decoration and most jobs such as bartender or cook hopeless and terrible

**Comment by PerfectTangent** [comment] 2021-07-11 13:23
Duplicate of #6824. Closing.

**Closed as completed by PerfectTangent** 2021-07-11 13:23 UTC
Labels: Type: Bug
