### ISSUE TITLE
Venus Mantraps kill you in under a second -> Rate limit attacks

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8505] opened 2022-03-27 08:38 UTC
### Description
Venus Mantraps are stupidly powerful at the moment. It seems there is no limit on how quickly they can melee attack you, meaning they can land 5+ slashes and kill you in under a second. Mobs should be subject to the same attack timing restrictions as players.

**Comment by PerfectTangent** [comment] 2022-03-27 12:30
duplicate of #7830.

**Closed as completed by PerfectTangent** 2022-03-27 12:30 UTC
Labels: Type: Feature
