### ISSUE TITLE
Using scrollwheel to zoom is reversed on Linux

### ISSUE THREAD

**Issue by jessicamaybe** [unitystation/unitystation#2908] opened 2020-02-06 04:06 UTC
In the Linux version, zooming using the scroll wheel is reversed. Scrolling down zooms in, scrolling up zooms out. Scrolling is also reversed in the settings menu.

**Comment by Coolsurf6** [comment] 2020-02-06 05:24
Met the lad who talked about that in game. Seems a bit wacky.

**Comment by jessicamaybe** [comment] 2020-02-06 06:23
Yea that was me, lol

**Comment by Nutjob** [comment] 2020-02-06 09:00
I can confirm this, got the same bug on Ubuntu 18.04; the same also happens while scrolling in the options menu.
The same bug also happens on others Unity games as Tabletop Simulator.

**Comment by x10an14** [comment] 2020-07-24 19:30
Same here, on Debian 10.

**Comment by jessicamaybe** [comment] 2020-10-04 06:23
It looks like this bug has been fixed on my end, it may have been a Unity issue?

**Comment by corp-0** [comment] 2020-10-04 13:55
If we get another confirmation, we close

**Comment by Nutjob** [comment] 2020-10-04 14:13
Seems to be fixed on my side too.

**Comment by corp-0** [comment] 2020-10-04 14:15
Awesome. No idea how or when it was fixed but good to know it was. Closing.

**Closed as completed by corp-0** 2020-10-04 14:15 UTC
Labels: Type: Bug, Affects only: Linux

**Comment by x10an14** [comment] 2020-10-04 18:44
What game was this again? Space Heaven?
