### ISSUE TITLE
input focus isn't properly deregistered when dragged away from command console

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3075] opened 2020-02-12 20:38 UTC
results in you not being able to do anything
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  open command console type in something
2.  get another player to drag you away so it disappears
3.  oobbserved lack of input

**Comment by NoooneyDude** [comment] 2020-05-25 02:43
Couldn't reproduce. It seems similar to #4077, which was fixed by #4264.

**Comment by vlandemart** [comment] 2020-05-25 11:41
True, this was fixed in #4264

**Closed as completed by vlandemart** 2020-05-25 11:41 UTC
Labels: Type: Bug
