### ISSUE TITLE
equipped with Ian's clothing and accessories (and some other companions)

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9025] opened 2022-07-31 14:45 UTC
In various versions of the SS13 code it is possible to equip Ian (and I believe the barman's monkey) with hats, and certain vests, such as bulletproof gillet.

**Comment by PerfectTangent** [comment] 2022-07-31 15:20
duplicate of #4426

**Closed as completed by PerfectTangent** 2022-07-31 15:20 UTC
Labels: Type: Feature
