### ISSUE TITLE
Clicking players always triggers drag doll

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1867] opened 2019-05-14 20:24 UTC
# Description
If you try to click on someone the drag doll will appear every time.

Drag doll:
![image](https://user-images.githubusercontent.com/4493127/57729321-cdfeb980-768d-11e9-9e5a-015f5660d544.png)

There should be a delay or a deadzone for dragging to stop single clicks unintentionally being registered as drags.

Requires #1845 to be fixed first

Also: the dragging seems to be more consistent using the host, using a client has some spots on the player which don't appear to trigger it

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get two players (1 host and 1 client)
2. Click on a player
3. Notice the drag doll pops up even if it was a single click

**Comment by chairbender** [comment] 2019-06-07 18:26
Possibly duplicate of #1918

**Closed as completed** 2019-06-12 12:14 UTC
Labels: Type: Bug, Status: In Progress
