### ISSUE TITLE
Paper window disappears after hovering container slot

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3407] opened 2020-02-28 14:25 UTC
video is self-explanatory:
![gif](https://user-images.githubusercontent.com/10403536/75556394-0d886d80-5a36-11ea-8cb2-f54414104d9d.gif)

**Comment by AutumnNova** [comment] 2020-03-03 04:25
is this not a duplicate of #3191 ?

**Closed as completed** 2020-03-15 22:09 UTC
Labels: Type: Bug, Good First Issue, Group: UI
