### ISSUE TITLE
A-ghosting on shuttle gets you stuck on station

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7493] opened 2021-10-01 01:51 UTC
### Environment
- Game Version: Staging 21093018
- OS Version: Arch Linux

### Detailed description of bug

First off when testing the shuttle console the image when traveling doesnt update and second after doing some movement on the shuttle when you A-Ghost and try to get back into your body you will get stuck into the station uable to move or go back. 

examples:

this was done on round 1
https://user-images.githubusercontent.com/80334192/135552920-2da8069e-9e7a-42e7-975b-f591b7149240.mp4

after that i tried exiting the game and joining back, this happened

https://user-images.githubusercontent.com/80334192/135553018-9211128e-e27e-404a-8c13-b1ce609fc60d.mp4

this was done on round 2 

https://user-images.githubusercontent.com/80334192/135553049-66a1e5c1-c5c3-4fdf-ad9c-4e0969ee69b0.mp4

tried the same behavior just like in round 1 exiting and joining back but the same issue didnt happened (further testing is required)

https://user-images.githubusercontent.com/80334192/135553139-b932a5ad-42d3-4f46-bce6-cd17d5c7ddc7.mp4

### Steps to reproduce

1. join staging
2. hop onto a shuttle and move around for a while
3. a-ghost and try to go back into your body
4. if the issue happens exit the game and join back to test if you get desync issues as show in the videos

**Comment by Atrocious-Augur** [comment] 2021-10-03 02:01
I think I found a related bug earlier today. A player was stuck in the shuttle chair, couldn't get out by unbuckling or turning RCS off, so I teleported them into the station on my A-Ghost, and they couldn't move still. I don't have any evidence documented since I was just playing casually and I think the relevant error messages were on that stuck player's side.

**Comment by PetMudstone** [comment] 2021-10-03 02:03
> 
> 
> I think I found a related bug earlier today. A player was stuck in the shuttle chair, couldn't get out by unbuckling or turning RCS off, so I teleported them into the station on my A-Ghost, and they couldn't move still. I don't have any evidence documented since I was just playing casually and I think the relevant error messages were on that stuck player's side.

Sounds similar to #6992.

**Comment by ThatDan123** [comment] 2021-11-02 21:47
Has this been reproduced recently? Aran has done a lot of work on movement, matrix and login stuff

**Comment by ThatDan123** [comment] 2022-07-19 21:25
Ghost movement has been redone, closing until reproduced (open new issue if it happens)

**Closed as completed by ThatDan123** 2022-07-19 21:25 UTC
Labels: Type: Bug, Status: Needs Reproduction, System: Admin
