### ISSUE TITLE
NREs when relogging into account after logging out of a round

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#4675] opened 2020-07-22 09:31 UTC
## Description
NREs occur when entering characters into a field of the `Account Login` window after logging out of a round.

### Detailed Bug Report
![nre](https://user-images.githubusercontent.com/6926225/88159752-d96e4d00-cc61-11ea-858b-c52cc8d910e5.gif)

### Steps to Reproduce
1. On a development build (`3921`), log in and join or host a round.
2. Leave the round by hitting escape and choosing `Logout`.
3. In the `Logged in: [Userame]` window, choose `Logout`.
4. Add additional characters to any form of the window and observe the NREs generated.

**Comment by PerfectTangent** [comment] 2021-08-21 23:08
is this still an issue?

**Comment by corp-0** [comment] 2021-08-21 23:23
can't reproduce and report is quite old. I'm closing.

**Closed as completed by corp-0** 2021-08-21 23:23 UTC
Labels: Type: Bug
