### ISSUE TITLE
Teleporting items on conveyorbelts

### ISSUE THREAD

**Issue by Borimino** [unitystation/unitystation#8496] opened 2022-03-26 21:14 UTC
When loading the Cargo Shuttle using the conveyorbelts, items that are comming into the shuttle on the last spot of the belt move across the screen from top-right towards the end of the belt as soon as the previous item is taken off the belt.

**Comment by MaxIsJoe** [comment] 2022-03-26 22:56
duplicate of #8357

**Closed as completed** 2022-03-26 23:27 UTC
