### ISSUE TITLE
Dead people are standing up

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#8297] opened 2022-01-30 17:31 UTC
-Dead people are standing up not lying down

**Comment by potatoalienof13** [comment] 2022-01-30 19:16
If it helps, you can recreate this by dragging a body from one matrix to another.

**Comment by Fogapod** [comment] 2022-09-15 09:32
a duplicate of https://github.com/unitystation/unitystation/issues/6691

**Closed as not planned** 2022-09-16 02:08 UTC
Labels: Type: Bug, System: Animation
