### ISSUE TITLE
Syndie shuttle starts with its lights off

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1751] opened 2019-04-16 12:02 UTC
# Description
![image](https://user-images.githubusercontent.com/701959/56207844-25295400-6026-11e9-925e-e319f27a7bc9.png)
All the lights seem to be off, but for the medical room on the bottom left. The switches dont seem to do anything

## Category
BUG 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Go to the syndie shuttle/spawn as one
2.Notice the darkness
3.Try to use the switches with no success

**Comment by Aranclanos** [comment] 2019-04-16 12:02
also the light tubes have the 'on' sprite

**Comment by fomalsd** [comment] 2019-04-16 12:05
@Bod9001 could you look into this again please? it's been like that for around 6 months now, I think

**Comment by Jibbajabbafic** [comment] 2019-04-16 14:49
Duplicate of #1390

**Closed as completed** 2019-04-23 11:47 UTC
Labels: Type: Bug
