### ISSUE TITLE
Light-emitting headwear doesn't emit light on spawn until re-equipped

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#4048] opened 2020-04-26 19:16 UTC
Engineer's hat doesn't emit light after spawning. You have to remove it and put it back to make it work

Please enter the steps to reproduce the bug or behaviour:  

1.  Join as Engineer
2.  See your hat not emitting light
3.  Re-equip it and see it emit light

**Comment by Ninjaboi8175** [comment] 2020-04-29 18:48
Can confirm this happens. I'll take a look at it later.

**Comment by Ninjaboi8175** [comment] 2020-05-04 10:35
From what I can tell this is caused by not calling AddLight() for each ClothingItem object that has a PlayerLightControl component when spawning the player in. It may normally get checked and called whenever inventory is moved but I don't think that happens upon spawn either. The player just gets assigned the equipment they need and circumvents this process.

I tinkered with it for a bit but had trouble getting `clothingItem.GameObjectReference` to return an assigned value. Probably gets assigned sometime after when I was checking it. For anyone that ends up wanting to try and resolve this, you'll likely need to either:

1) Have a new method such as StartLightEmissions() in Equipment.cs that checks all the children objects of the player object for ClothingItem components and iterate through them to see if they have PlayerLightControl components assigned. If so you'd grab PlayerLightData and call and pass it to AddLight() on the player's LightEmissionPlayer component. Then you'd have to have PlayerManager call it after spawning and assigning control to the player ( or call the method whenever clothingItem.GameObjectReference is already assigned ).
OR
2) Find some way to do it in Equipment.cs's Awake() method given how that already iterates through clothingItem objects for the player. Might save some work.

**Comment by Ranzarth** [comment] 2020-05-04 14:17
Needs to have the action system implemented into it including seclight and other flashlights
https://github.com/unitystation/unitystation/pull/3310

**Comment by NoooneyDude** [comment] 2020-07-23 11:39
Headwear that is supposed to emit light no longer does so at all, regardless of if you unequip them, click on them, throw them away and put them back on your head - at least with the Engineer's hardhat.

**Comment by corp-0** [comment] 2020-07-23 11:43
we recently had this related pr #4631

**Comment by NoooneyDude** [comment] 2020-08-30 08:38
Closing this issue because light-emitting headwear can now be toggled, and the toggling works fine.

**Closed as completed** 2020-08-30 08:38 UTC
Labels: Type: Bug
