### ISSUE TITLE
Fire airlocks are silent and invisible 

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7587] opened 2021-10-16 14:45 UTC
### Environment
- Build Version is: 21101607. 
- OS Version:_Mac_Catalina_ 10.15.7

### Detailed description of bug

Airlocks connected to fire alarms do not appear in a closed state nor do you hear them opening or closing.
### Steps to reproduce

1. Goto a fire alarm and engage it
2. Attempt walking through an airlock that it controls. (Hit the fire alarm again, or use a pry bar to open them
![Screen Shot 2021-10-16 at 9 37 29 AM](https://user-images.githubusercontent.com/92214971/137591757-f25fd517-54d1-4818-867f-602f76816af2.png)
)

**Comment by Q4ik** [comment] 2021-10-16 15:11
No fire alarm animation either

**Comment by Aranclanos** [comment] 2021-10-31 08:53
Can't reproduce

**Comment by mmails** [comment] 2021-10-31 08:54
Can't reproduce either

**Comment by ThatDan123** [comment] 2021-10-31 22:40
> Can't reproduce

Did you test late joining when they are already closed?

**Comment by Aranclanos** [comment] 2021-11-01 12:47
yes

**Comment by ThatDan123** [comment] 2021-11-01 12:49
Unreproducible so closing

**Closed as completed by ThatDan123** 2021-11-01 12:49 UTC
Labels: Type: Bug
