### ISSUE TITLE
players able to chat while in crit

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1662] opened 2019-03-24 00:35 UTC
# Description
Players are able to chat while in crit state
(Currently only discovered on headless)

this is possibly brought up again after multiple types of crit were brought up
## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. go into a crit state
2. attempt to talk

**Comment by Fishfish458** [comment] 2019-03-24 00:35
I'm going to check this one out myself, I just wanted to make sure it was listed as an issue prior in case

**Comment by DooblyNoobly** [comment] 2019-03-24 02:48
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by fomalsd** [comment] 2019-03-24 09:55
Are you sure you were able to chat in **hard** crit (not able to move)?
You can "whisper" while in soft crit (you'll have italic fonts)

**Comment by fomalsd** [comment] 2019-03-24 11:24
Couldn't reproduce this on steam server. 
As intended, you can whisper in soft crit but can't chat at all in hard crit.
Closing

**Closed as completed by fomalsd** 2019-03-24 11:24 UTC
Labels: Type: Bug
