### ISSUE TITLE
Unrealstation cargo shuttle gets stuck when it tries to leave.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6421] opened 2021-04-26 22:58 UTC
### Environment
- Game Version: latest develop, tested in editor

### Detailed description of bug

When the Cargo shuttle in Unrealstation attempts to leave, it rotates into the docking collar and gets stuck.

### Steps to reproduce

1. send the cargo shuttle on the cargo console
2.  the shuttle rotates into the station when it tries to leave

![unrealcargoshuttle](https://user-images.githubusercontent.com/68730437/116161145-44512680-a6c1-11eb-87dd-7bf92318575d.png)

**Comment by PerfectTangent** [comment] 2021-04-26 22:59
I am currently working on a PR for unrealstation. I will push my changes and when I have time, I will take a look at this problem. Just guessing, the evac shuttle may have the same problem.

**Comment by pyrosshade** [comment] 2021-06-06 02:41
this is still a thing, just in different form, crago shuttle returns, but always docks in the exact same fucky way. 
![image](https://user-images.githubusercontent.com/14188696/120910715-1b706980-c64f-11eb-98de-9e2c757700d6.png)

**Comment by pyrosshade** [comment] 2021-06-06 03:26
when shuttle is ordered to leave, it's sideways like so
![image](https://user-images.githubusercontent.com/14188696/120911429-7ad17800-c655-11eb-92d8-d7011fe8edc3.png)
but somehow it's considered at centcomm

**Comment by pyrosshade** [comment] 2021-06-06 03:46
when sent from centcomm back to station, it just turns once countdown is done, making it possible to get stuck
![image](https://user-images.githubusercontent.com/14188696/120911818-35fb1080-c658-11eb-891b-f113ec8431dd.png)

**Comment by corp-0** [comment] 2023-03-06 15:47
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

Also UnrealStation is currently abandoned.

**Closed as completed by corp-0** 2023-03-06 15:47 UTC
Labels: Type: Bug, No Coding, Group: Mapping
