### ISSUE TITLE
Scrubbers/ vents bad layering

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6688] opened 2021-06-04 23:43 UTC
Linux - staging

Scrubber/vent pipe-ends are visible on top of tiles again 

![Screenshot at 2021-06-04 19-40-30](https://user-images.githubusercontent.com/55299415/120872559-1804b180-c56d-11eb-82ae-daa248ded12d.png)

**Comment by pyrosshade** [comment] 2021-06-05 01:02
pipe-ends will need their sorting group changed

**Comment by corp-0** [comment] 2021-06-10 01:03
is this only over wood flooring? I can't find any instance of this bug in square right now.

**Comment by corp-0** [comment] 2021-06-10 01:07
![image](https://user-images.githubusercontent.com/43683714/121448933-ab235a00-c966-11eb-871a-9e551ab4a341.png)
![image](https://user-images.githubusercontent.com/43683714/121448942-b080a480-c966-11eb-80b9-c35885c56212.png)
Square

**Comment by corp-0** [comment] 2021-06-10 01:10
Walked around Unreal as well, I can't reproduce

**Comment by corp-0** [comment] 2021-06-10 01:21
![image](https://user-images.githubusercontent.com/43683714/121449793-803a0580-c968-11eb-9c10-9f8a00e1da37.png)
this is fall for me right now on staging. I'm not sure if this is map related or it is related to me connecting to an ongoing round. Anyways, I'm reopening and changing the validity for the contest.

**Comment by ThatDan123** [comment] 2021-08-09 22:32
It was map related but it seems like they've all been replaced now, so gonna close it

**Closed as completed by ThatDan123** 2021-08-09 22:32 UTC
Labels: Type: Bug, Group: Spriting, ValidForContest
