### ISSUE TITLE
Fire can turn space tiles into hull tiles

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2481] opened 2019-12-22 14:46 UTC
# Description
probably something to do with it updating in space

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.make massive station wide fire
2.observe the extra hull tiles

**Comment by fomalsd** [comment] 2019-12-24 09:46
what do you mean by hull tiles? got a screenshot?

**Comment by chairbender** [comment] 2019-12-24 16:28
It turns them into scorched floor or base tiles, can't remember which. Its pretty much only due to the scorch effect logic so it's pretty easy to remove that if there's no tile to scorch.

**Comment by NoooneyDude** [comment] 2020-07-22 11:00
Is this still an issue? Couldn't reproduce, but I may not be doing it correctly.

**Comment by ThatDan123** [comment] 2020-07-31 19:42
Hasnt been reported, and ive never seen it. Also NooneyDude couldnt reproduce it, so closing.

**Closed as completed by ThatDan123** 2020-07-31 19:42 UTC
Labels: Type: Bug
