### ISSUE TITLE
[BUG] Admin - Heal player :pill: 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10117] opened 2023-10-09 07:39 UTC
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game  Version
- 100461 - 23.10.07.15

### I was
Server (local Host)
HOP
On Ministation 
### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?
the heal player button in the player manager interface heals neither
- Hunger
- Radiation
- genetic mutation
- lost limbs
- 

but heals death ....

**Comment by MaxIsJoe** [comment] 2023-10-09 08:34
This isn't a bug, this is a missing feature and is a duplicate of #7593 .

**Closed as completed by MaxIsJoe** 2023-10-09 08:34 UTC
