### ISSUE TITLE
No validation in "Create an account" form

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2226] opened 2019-10-24 23:30 UTC
# Description
There seems to be no validation  in the "Create an account" form. There is also no info how long login/password should be.

## Category
BUG 

## Detailed Bug Report
If you try to create an account with no password, short password or invalid email, you will stuck in "Please wait..." state. After a while it will print "Response timed out, please try again"

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Open Lobby scene
2. Click on "Create"
3. Leave all fields empty or enter some trash
4. Click "Next"

**Comment by NoooneyDude** [comment] 2020-07-22 09:20
I couldn't reproduce the Response timed out issue, validation does appear to occur now. This issue can probably be closed.

**Comment by corp-0** [comment] 2020-11-20 01:53
closing, if the problem persists, feel free to reopen.

**Closed as completed by corp-0** 2020-11-20 01:53 UTC
Labels: Type: Bug, Affects only: Hub
