### ISSUE TITLE
Mobs don't take damage from thrown objects

### ISSUE THREAD

**Issue by waffielz** [unitystation/unitystation#8351] opened 2022-02-11 22:47 UTC
### Environment
- Game Version: 2201002
- OS Version: Windows 10

### Detailed description of bug

Mobs don't take damage from thrown objects lmao

### Steps to reproduce

1. pick up somthing
2.  yeet
3. ???

https://user-images.githubusercontent.com/15893891/153681034-973c6e56-10b6-45ec-afd9-9fdac75fc981.mp4

**Comment by Maximal98** [comment] 2022-02-11 23:11
now this is a quality issue

**Comment by PerfectTangent** [comment] 2022-02-12 04:12
duplicate of #6742. Closing.

**Closed as completed by PerfectTangent** 2022-02-12 04:12 UTC
Labels: Type: Bug
