### ISSUE TITLE
quantum pads dont keep you pulling things

### ISSUE THREAD

**Issue by techpriest154** [unitystation/unitystation#6703] opened 2021-06-05 11:45 UTC
### Environment
- Game Version: 21060314
- OS Version: windows 10, latest

### Detailed description of bug

when i walk through quantum pads while grabing something both me and the object are teleported, however i stop grabbing object when i do this, this happens for everything i have used so far crates, corpses, items, to name a few
![image](https://user-images.githubusercontent.com/78688207/120893882-5e115200-c60d-11eb-996b-d9b4638e3bc8.png)

### Steps to reproduce

1. drag something
2. walk through a quantum pad, lavaland or standard one, dosent matter

**Comment by Pockets-byte** [comment] 2021-06-05 15:55
duplicate of #5061

**Comment by PerfectTangent** [comment] 2021-06-06 11:13
closing in favor of #5061.

**Closed as completed by PerfectTangent** 2021-06-06 11:13 UTC
Labels: Type: Bug
