### ISSUE TITLE
stacking interaction code broke on headless

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2539] opened 2020-01-05 12:51 UTC
# Description
 when testing out the headless serverThe stacking Interaction was broken, the only way I found of making them stack properly was Placing one stack on the floor then dragging the other stack over it and That made them stack

## Steps to Reproduce
IDK If it's easily reproducible

**Comment by JesterX666** [comment] 2020-01-05 21:15
Likely a duplicate of Can't pick-up/combine stackable item #2518

**Comment by Jibbajabbafic** [comment] 2020-01-23 22:41
Fixed if #2518 is fixed already

**Closed as completed by Jibbajabbafic** 2020-01-23 22:41 UTC
Labels: Type: Bug, Status: Needs Reproduction
