### ISSUE TITLE
Not stackable glass sheet with any intent.

### ISSUE THREAD

**Issue by ReiderJack** [unitystation/unitystation#3386] opened 2020-02-27 14:20 UTC
![UnStackable](https://user-images.githubusercontent.com/42844726/75453638-40265d80-5985-11ea-93a5-bb22dd1128f5.gif)

**Comment by JesterX666** [comment] 2020-02-27 17:34
I've seen this before.  It happened when someone accidentally removed all Stackable component "Stacks With" entries.  Might be the issue.

**Comment by Tjarr737** [comment] 2020-02-29 07:40
Are we sure this issue still exists? Does this happen to all stacks of glass sheets? I couldn't reproduce it (in the editor).
(The stackable component of the glass sheets seems fine too.)

**Comment by AutumnNova** [comment] 2020-02-29 07:42
it seems inconsistent

**Comment by ReiderJack** [comment] 2020-02-29 10:46
![NotStacking](https://user-images.githubusercontent.com/42844726/75606028-cf548200-5af9-11ea-9ce0-6b89ace516f8.gif)
checked today on USA 3 server

**Comment by NoooneyDude** [comment] 2020-09-08 10:00
This is probably no longer an issue since the old material prefabs have been deleted. Closing, but feel free to reopen if this is still an issue.

**Closed as completed by NoooneyDude** 2020-09-08 10:00 UTC
Labels: Type: Bug
