### ISSUE TITLE
Disarming Fired Guns Drops A Reloaded Gun

### ISSUE THREAD

**Issue by mudzbe** [unitystation/unitystation#2679] opened 2020-01-20 09:09 UTC
When you disarm someone with a gun, even if they have fired all the ammo in it. After disarming them the gun will spawn fully loaded.

This has been replicated with the L96, heirloom handgun, double barrel, detective revolver and likely every other gun.

Steps to Reproduce

1.  Have someone fire all ammo in the gun.
2.  Disarm that person.
3.  Pickup the gun and fire it.

Found by me and BowStache

**Comment by nikopetr** [comment] 2020-01-20 11:40
This one looks kinda easy to fix. Can you guys give me a guidance on which classes should I look to so I can get a look on this?

**Comment by chairbender** [comment] 2020-01-21 00:32
I'm not sure, due to the need for client prediction the logic involving gun ammo is actually pretty complicated.

If you want to try, look at Gun for the actual gun component, and note that Gun magazines go into their ItemStorage (index 0 slot).

My guess is that when gun is being dropped due to disarmament, the gun for a moment sees that its mag slot is empty and tries to spawn a new mag, overwriting the old one. Just a guess.

**Comment by mudzbe** [comment] 2020-01-22 02:31
I think it spawns a new gun with fully loaded ammo. Might have to check gun IDs though to see if they are the same gun just with more ammo, worth looking into.

**Comment by chairbender** [comment] 2020-01-22 02:33
It should be calling Inventory.ServerDrop which isn't supposed to spawn a new gun, just take the one out of their hand.

**Comment by JesterX666** [comment] 2020-02-08 02:03
Was not reproduced

**Comment by RedlineTriad** [comment] 2020-03-10 12:06
Closing for now, reopen if it is still happening.

**Closed as completed by RedlineTriad** 2020-03-10 12:06 UTC
Labels: Type: Bug, lol, Status: Needs Reproduction
