### ISSUE TITLE
Change UI scale

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#6548] opened 2021-05-17 21:53 UTC
### Description

change UI / GUI scale in game graphique option.
for 11" and 30" 4k screen ...

**Comment by NoooneyDude** [comment] 2021-05-18 05:42
Duplicate of #2047.

**Comment by NoooneyDude** [comment] 2021-05-18 05:43
Edit: this is about scaling, not resolution. Closely related to #2047.

**Comment by Fr-Dae** [comment] 2021-05-18 05:48
resolution are the maximal the screen can accept/ display .
Ui scaling are user preferencie and change for any player.
according to their preferences / habits, abilities, or handicaps.

**Comment by PerfectTangent** [comment] 2021-11-01 17:22
closing in favor of #7687

**Closed as completed by PerfectTangent** 2021-11-01 17:22 UTC
Labels: Type: Feature, Group: UI
