### ISSUE TITLE
[BUG] Immortality Glitch

### ISSUE THREAD

**Issue by longhall** [unitystation/unitystation#10313] opened 2024-03-23 22:36 UTC
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

24032301

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

became immortal when i did a weird surgery

### What should have happened instead?

should not become immortal

### Steps to reproduce the issue

1. implant synthetic lungs into chest
2. you are now unkillable

### Additional context

this is a pretty serious bug that could easily ruin entire rounds

**Comment by corp-0** [comment] 2024-03-23 22:50
damn, thanks for reporting it. We will check out what's going on

**Comment by MaxIsJoe** [comment] 2024-05-26 12:25
Was testing this just recently and I've found out a possible reason as to why this happens:

Something related to circulation and or a health system keeps updating the heart even after it's forced to stop, the updates cause the heart to basically restart because it thinks that something is reviving it.

You can actually see the effects of this by trying to force the player to die without any damage, calling `Death()` directly from LHMB just causes the player to momentarily die before their heart restarting (and thus reviving them right after they die)

**Comment by longhall** [comment] 2024-05-27 21:37
edited my first post because it was wrong. the problem looks like its something specifically wrong with the code for synth lungs, because when you implant human lungs nothing happens.

**Comment by MaxIsJoe** [comment] 2024-09-04 06:35
I assume this has been fixed since two playtest sessions have passed and no one reported it again.

**Comment by corp-0** [comment] 2024-09-04 08:13
Since there are reproduction steps, we should try to replicate before closing. I don't know if @Bod9001 did anything relates to this bug

**Comment by MaxIsJoe** [comment] 2024-10-03 10:52
Hasn't been reproduced.

**Closed as completed by MaxIsJoe** 2024-10-03 10:52 UTC
Labels: Type: Bug, Status: Needs Reproduction, Priority: Urgent
