### ISSUE TITLE
Clicking On Doors Doesnt Open Correct Door

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6557] opened 2021-05-18 20:35 UTC
Sometimes clicking on doors doesnt open the correct door see:

https://user-images.githubusercontent.com/56727168/118720022-03ac7f00-b821-11eb-8a66-f8a0f9465a86.mov

**Comment by MaxIsJoe** [comment] 2021-05-18 20:52
There has been a few interactions lately where if you click something you end up clicking on something else entirely.
I thought this was fixed since I didn't encounter it last couple of times I was on staging but apparently it still happens.

Edit: Biggest two I could recall is clicking on two lockers next to each other and opening the wrong one and the other is me trying to pick up something but only it working from afar or picking the wrong item.

**Comment by DTraitor** [comment] 2021-05-19 15:44
Accidentally managed to reproduce this bug. You need to come to HoP office on fall. Then you hold your mouse over EVA storage and move it to the locker. That's all.
Now what I managed to learn:
1. It's not connected with your postition on the server;
2. It happens to items too (EVA helmet in that storage had the same issue);
3. This error did not happen with the locker, so when I moved my mouse to the storage, I could open it.

**Comment by ThatDan123** [comment] 2021-05-19 15:46
Some weird cache issue maybe?

**Comment by DTraitor** [comment] 2021-05-19 15:52
I just restarted the game and I couldn't reproduce it in that place

**Comment by pyrosshade** [comment] 2021-05-29 01:43
Has this been reproduced?

**Comment by PerfectTangent** [comment] 2021-07-07 12:19
this has not been reproduceable after several people have tried. Gonna close it for now.

**Closed as completed by PerfectTangent** 2021-07-07 12:19 UTC
Labels: Type: Bug, Status: Needs Reproduction, System: Interaction
