### ISSUE TITLE
Instant summons will summon any container the object is in, including players

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8436] opened 2022-02-26 23:32 UTC
### Detailed description of bug

If you use instant summons on an item that is in an object's container storage or another player's inventory, it will summon that object or that player. It should just remove the item from the object or player's inventory.

**Comment by craftxbox** [comment] 2022-02-28 16:53
Working as intended:tm: /s

**Comment by corp-0** [comment] 2022-02-28 17:22
You can't deny it is kind of cool

**Comment by NoooneyDude** [comment] 2022-05-30 01:55
This was actually my intention : )

```
// backpack, box, player etc, or the item itself if not in storage
GameObject objectToSummon = GetItemOrRootStorage(markedItem.gameObject);
```

 I think it is more interesting. What do others think?

**Comment by NoooneyDude** [comment] 2022-05-30 02:00
Though admittedly it does mean you can't rip out someone's marked organ...

**Comment by wraith-54321** [comment] 2022-05-30 03:11
could make it teleport the item to your hand and then the person to you

**Comment by AtnerNT** [comment] 2023-07-20 06:39
Think this can be closed as is intended functionality

**Comment by MaxIsJoe** [comment] 2023-07-20 09:56
I'll ask Bod if he wants to leave this in as intended functionality.

**Comment by MaxIsJoe** [comment] 2023-07-20 09:58
he said yes

**Comment by MaxIsJoe** [comment] 2023-07-20 09:58
![image](https://github.com/unitystation/unitystation/assets/34368774/7fc5b97f-929f-4f2f-a67c-a6a60279cb7b)

**Closed as completed by MaxIsJoe** 2023-07-20 09:58 UTC
Labels: Type: Bug
