### ISSUE TITLE
Outpost and Box Updates

### ISSUE THREAD

**Issue by Ranzarth** [unitystation/unitystation#4145] opened 2020-05-05 02:37 UTC
## Description

Decided to do problems, suggestions, and improvement tickets on every map including outpost and also box. Most of the outpost stuff I wrote here is for me to remember to get to at a later date.

### Outpost

- [x]  Bridge needs to be redone, too big.
- [ ]  Telecomms needs to be readded.
- [ ]  Gravity Room needs to be added.
- [x]  Medical needs some tweaks to the design.
- [x]  Engineering needs a renovation, looks weird with the hacked on sec office.
- [x]  Science needs to be extended, some of the rooms like toxins and robotics are too small.

### Box

- [x] Self destruct terminal should be moved to the vault
- [x] Bridge needs blast doors on its two side entrances
- [x] A button connecting the front doors of medical should be placed on the front desk
- [x] A button inside should also be connected to the front doors so anyone can let themselves out.
- [x] Needs a syndicate outpost
- [x] Still has the old V1 Syndicate shuttle

Comment below if something should be added/removed/changed

**Comment by ThatDan123** [comment] 2020-05-05 10:10
Box
-Bridge needs blast doors on its two side entrances

The reason i didnt map those was when i did it caused a really weird looping air sound, needs to be investigated more as it might be fixed.

**Comment by ThatDan123** [comment] 2020-05-09 17:09
Fixed up boxstation, blast doors seem to be ok now.

**Comment by NoooneyDude** [comment] 2020-05-11 11:33
**_Complete_** For boxstation, morgues exist in security and robotics, but not in medical's main morgue room.

**Comment by corp-0** [comment] 2023-03-06 15:47
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

If anything of this list is still a problem, it should be reported using said template.

**Closed as completed by corp-0** 2023-03-06 15:47 UTC
Labels: Type: Feature, No Coding, Group: Mapping
