### ISSUE TITLE
Respawning player as Antag does not connect to Traitor Uplink on PDA

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#5215] opened 2020-09-28 11:58 UTC
## Description
Reported by LastCaptainBonk, respawning player as Antag (traitor/nukie) does not connect to Traitor Uplink on PDA.
### Detailed Bug Report
PDALogic.cs handles the TryInstallUplink inside the OnStartServer function, as the PDA is an item. I think adding in a line inside the SetAntagDetails inside SpawnAntag.cs underneath objectives creation should give the uplink code. However, doing this would probably set the PDA's uplink twice on roundstart. It's more likely something to do with the coroutine that handles the delay before calling OnStartServerDelayed not getting called.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Spawn in
2.  Smite self
3.  Respawn as a Traitor
4.  Get no uplink code in chat.

**Comment by Aranclanos** [comment] 2020-10-01 18:44
Tested on editor and on staging, I can't reproduce

**Comment by corp-0** [comment] 2020-10-01 23:13
@Aranclanos you get the uplink when respawning as antag? I'm sure I didn't touch anything about that logic when I did the respawn thing

**Comment by Aranclanos** [comment] 2020-10-01 23:38
Yes, its mind-based and I did those 
Basically the PDA checks if the MIND is an antag

**Comment by NoooneyDude** [comment] 2020-12-24 07:14
The PDA itself determined whether it should install the uplink and so wasn't affected by the antagonist respawn issue described in #5776. However, this was changed in PR #5774 to lay the responsibility onto the `AntagManager`  and so this issue _did_ become relevant. It is fixed in #5776.

**Closed as completed** 2020-12-24 18:28 UTC
Labels: Type: Bug
