### ISSUE TITLE
Global Hit Sound

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6799] opened 2021-06-15 20:18 UTC
Using a toolbox on a windoor causes a global hit sound.

Other objects do it too

1. Get toolbox
2. Hit Windoor
3. Sound will be global, heard anywhere on the server

**Comment by pyrosshade** [comment] 2021-06-15 21:01
duplicate of #6725

**Comment by corp-0** [comment] 2021-06-15 21:02
not really. They are related but are talking about different issues. This one in particular is only about glass hit being global.

**Comment by pyrosshade** [comment] 2021-06-15 21:08
I'll close mine, hit sounds on glass is what it's boiled down to at this point.

**Closed as completed** 2021-06-16 10:24 UTC
Labels: Type: Bug, Priority: High
