### ISSUE TITLE
Ctrl + arrow /Ctrl Qwsd don't rotate, juste move

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8863] opened 2022-06-16 19:28 UTC
**Environment**

**- Game Version:** 22-06-15-20
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
Head Officer, in FallStation, in Office, tmoving

**Manipulation**
Ctrl QWSD or Ctrl arrow

**Result**
move

**Expected**
turn on direction, like previous update

**Comment by Fr-Dae** [comment] 2022-06-16 19:28
![Peek_16-06-2022_21-25](https://user-images.githubusercontent.com/23202421/174149697-e1466463-8546-4e65-8922-137b633715dd.gif)

**Comment by corp-0** [comment] 2022-07-17 09:07
duplicate of #8753

**Closed as completed by corp-0** 2022-07-17 09:07 UTC
Labels: Type: Bug
