### ISSUE TITLE
Job slots still occupied after round restart or player disconnecting B: 30

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1663] opened 2019-03-24 01:09 UTC
# Description
When users disconnect, the job slot they chose is still marked as occupied and the job list is not updated, preventing anyone else from taking on the job. The player count is also not reduced on the job screen.

Additionally, when the round is restarted, the job list doesn't clear out and all the slots that were occupied the previous round still show as occupied. It should show as completely empty at the start of a new round.

(Currently only discovered on headless)

**Comment by DooblyNoobly** [comment] 2019-03-24 02:51
Bounty of 30 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by fomalsd** [comment] 2019-03-24 09:57
Suspected duplicate of #1580

**Closed as completed** 2019-03-25 09:02 UTC
Labels: Type: Bug, Bounty
