### ISSUE TITLE
Handcuffs stop player movement B: 35

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2032] opened 2019-07-18 19:58 UTC
# Description
Players should still be able to move when handcuffed, but any hand interactions should be disabled (in inventory and in the world). 

The only time they can't move is if the player is being dragged by someone else as well. The handcuffed player shouldn't be able to break pulls either.

Edit: 
When Doobly made #1935 he specified that cuffs should stop movement which isn't the case in /tg/

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get handcuffed
2. Try to move

**Comment by JaytleBee** [comment] 2019-07-18 20:00
For clarity, this is intended behaviour that Doobly specified in #1935:

> Stop player movement input from being allowed if [the player is cuffed]

**Comment by Emma3DSS** [comment] 2019-07-23 00:20
Fixing this

**Comment by Brizzzle1738** [comment] 2019-11-18 20:43
Is this a bug? May have found a fix, however it seems that when handcuffs were created it was supposed to stop player movement input.  Has the design of handcuffs changed to where a player is able to move when handcuffed?

**Comment by chairbender** [comment] 2019-11-18 21:19
@Brizzzle1738 the description in the ticket is still correct about what needs to be done. Note that I have already made it impossible to interact with things when cuffed in #2281 (which is not yet merged but should be soon), so all that's left to do is prevent player movement and pull breaking when cuffed, but allow them to move otherwise.

**Comment by chairbender** [comment] 2019-11-20 04:29
@Brizzzle1738 just an update, I would suggest holding off on this until #2281 is merged as I'm making some changes to interaction / movement validation

**Comment by DooblyNoobly** [comment] 2019-12-04 08:45
Contributor will receive a bounty of 35usd on a successful merge of a solution that resolves the issue above.

**Closed as completed** 2019-12-22 01:03 UTC
Labels: Type: Bug, Bounty, Good First Issue, Priority: High, System: Movement
