### ISSUE TITLE
Singularity causes gibbed player to not become ghost

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6351] opened 2021-04-11 03:40 UTC
### Environment
- Game Version: 21041100
- OS Version: MacOSX

### Detailed description of bug

Dying in a singularity causes a player that can't aghost to have their camera stick to the spot they died in without a body, being unable to become a ghost.

![Screen Shot 2021-04-10 at 8 36 10 PM](https://user-images.githubusercontent.com/61613068/114291495-b3c9e380-9a3c-11eb-9b84-4aac7f03b0e7.png)

### Steps to reproduce

1. Create a singularity
2. Die in it

**Comment by wraith-54321** [comment] 2021-04-11 04:12
there are so many bugs with ghosts I feel we may just need to rework the way they work

**Comment by NoooneyDude** [comment] 2021-04-11 04:15
Indeed the player mind does need a rework to better accomodate things like `possess`, which will likely affect ghosts to some extent.

**Comment by PerfectTangent** [comment] 2021-04-11 05:09
Also needed for things like the AI and blob. It's something I'd like to make a top priority once the feature freeze is over.

**Comment by ThatDan123** [comment] 2021-05-17 15:46
Is this still an issue? Cant reproduce in editor unless its a client only issue

**Comment by ThatDan123** [comment] 2021-05-17 15:52
Cant reproduce on staging so closing

**Closed as completed by ThatDan123** 2021-05-17 15:52 UTC
Labels: Type: Bug
