### ISSUE TITLE
norme UTF-8 chat

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9202] opened 2022-09-04 11:19 UTC
In IT, and even more so on international projects, it is important to respect certain standards.

especially the UTF8 for all that is not English-speaking.
I noticed this problem while working on the Russian tutorial prototype, I first thought it was an encoding problem on my side, but in fact it's general to the game. 

The dialogue bubble displays special characters correctly, like Cyrillic or Japanese. 

But not the game chat.
This disables all possible communication for non-English speakers. 

If you could manage the in-game chat encoding to support utf-8, that would be cool, thanks. 
![image](https://user-images.githubusercontent.com/23202421/188310658-1641f81a-ea54-44b2-bdb9-3c400d6c7c6d.png)
![image](https://user-images.githubusercontent.com/23202421/188310665-a7e36c24-fc16-4e92-ab5f-224ef7f69254.png)

**Comment by NoooneyDude** [comment] 2022-09-04 12:56
Duplicate of #7023 (which is a duplicate of #6774).

**Closed as completed by NoooneyDude** 2022-09-04 12:56 UTC
Labels: Type: Bug
