### ISSUE TITLE
Account name doesn't work for login

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#2043] opened 2019-07-20 17:32 UTC
# Description
The login popup window asks for an email and doesn't accept the acc name, which is asked on the creation of the account

## Category
BUG

**Comment by DooblyNoobly** [comment] 2019-07-20 21:41
This isnt a bug. You need to use your email for login. Its by design. Your username is actually your display name or OOC name. Ill change the wording so it doesnt say username in creation screen

**Comment by Jibbajabbafic** [comment] 2019-09-22 12:50
Fixed in latest develop

**Closed as completed by Jibbajabbafic** 2019-09-22 12:50 UTC
Labels: Type: Bug
