### ISSUE TITLE
Door closing on player will suffocate them

### ISSUE THREAD

**Issue by Aestras** [unitystation/unitystation#1734] opened 2019-04-14 12:23 UTC
# Description
On the rare occasion that a door closes on you, usually from passing between them too often, it can close on you, which would be fine since it immediately reopens, but in the tick that it's closed for, it suffocates players inside it.
## Category
BUG or TODO?
BUG
## Detailed Bug Report
![GIF3](https://user-images.githubusercontent.com/15038188/56092783-f96f6800-5e85-11e9-9bee-703f58d7e3b9.gif)
This tick of damage does 3 Oxy damage to whoever is unlucky enough to get snagged.
This was done on a local client.
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Walk in and out of a door
2.Wait for it to close on you
3.Try not to bleed to death

**Comment by Aranclanos** [comment] 2019-04-14 12:38
dupe of https://github.com/unitystation/unitystation/issues/1689

**Comment by Aestras** [comment] 2019-04-14 12:38
I'm an idiot

**Closed as completed** 2019-04-14 12:38 UTC
