### ISSUE TITLE
You cant set a knife down on a table.

### ISSUE THREAD

**Issue by Epicworlds** [unitystation/unitystation#187] opened 2017-03-10 00:57 UTC

**Comment by krille90** [comment] 2017-03-11 14:00
it works for me. Maybe there are now hidden bugs that prevented that (or it was already fixed)
Since it's not reproducible, I will close this issue for now.
If anybody has this issue again, try to find out under which circumstances it happens and give a short description.

**Closed as completed by krille90** 2017-03-11 14:00 UTC
