### ISSUE TITLE
Cannot drag cargo crates from the shuttle

### ISSUE THREAD

**Issue by HenryBlackie** [unitystation/unitystation#2034] opened 2019-07-19 09:03 UTC
# Description
Cargo crates cannot be dragged from shuttle

## Category
BUG

## Detailed Bug Report
When I try to drag a container off the cargo shuttle it'll  slide back on to the shuttle every time it leaves. I have tried going through the doors and dragging it through the open shutters and it did the same thing every time. I also tested multiple different crates (beer and baton) and both did the same.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Order cargo using shuttle
2. Open shutters and doors
3. Try to drag container through doors or walkways.

**Comment by 0xJoey** [comment] 2019-07-20 13:42
Messing around with it a bit, there seems to be some issue with atmos between the airlock and the shuttle. It seems the shuttle is getting depressurized.

![image](https://user-images.githubusercontent.com/345122/61579024-c7fade00-aaff-11e9-9ec0-5fae713fed3b.png)

I managed to get it out by going up and then right, but you'll notice that you'll get a message that you don't have enough oxygen.

![image](https://user-images.githubusercontent.com/345122/61579010-9bdf5d00-aaff-11e9-81a6-3a1c51b90301.png)
Also, when in this configuration, I can't right-click interact with the crate.

**Comment by HenryBlackie** [comment] 2019-07-26 10:24
I'd agree with 0xJoey, it does seem like objects get drawn towards the door.

I was messing about earlier with this and accidentally opened one of the crates, the contents was dragged to the white airlock door. I don't think I ever got any oxygen warnings though.

I've added some footage of when I was messing around, in case anything helps.

https://youtu.be/B3K3XLdeWuk

**Comment by fomalsd** [comment] 2019-07-31 14:35
Could you enable pressure gizmos in editor (Window - Matrix Check) and try again? 
Was unable to reproduce constant wind like in your video
![GIF0](https://user-images.githubusercontent.com/10403536/62220234-3dd43480-b39f-11e9-8a65-bd51267f2cc7.gif)

I suspect it's at least partially because of the way how cargo gate is designed – it needs another pair of shutter on the station's side to avoid depressurization inside the gate that happens each time when shuttle leaves

**Comment by HenryBlackie** [comment] 2019-07-31 19:50
I've just spent the last 10 minutes trying on the newest version and I can't recreate it any more either, with the shutters both open and closed.

I've got footage I can upload if you want, but it's essentially the same as yours. The airlock depressurises during transit, but once a door has been opened everything stabilises.

**Comment by fomalsd** [comment] 2019-08-09 14:26
Closing this, will reopen if someone manages to reproduce this again

**Closed as completed by fomalsd** 2019-08-09 14:26 UTC
Labels: Type: Bug
