### ISSUE TITLE
Throwing does way too much damage B: 25

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1665] opened 2019-03-24 01:18 UTC
# Description
Throwing something (at least from a client to another client) is usually a one hit kill.

Most likely this is not due to how throwing damage is calculated, rather it is due to the object hitting the player multiple times.

Expected behavior is that damage from throwing is only applied once and doesn't instantly crit / kill you.

Only reproduced on headless so far.

**Comment by DooblyNoobly** [comment] 2019-03-24 02:52
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Aranclanos** [comment] 2019-03-24 21:01
Can't reproduce

**Comment by NextThang** [comment] 2019-03-24 21:27
Yeah, I was trying it a little bit as well, but I couldn't just straight up kill someone by throwing someone at them. Maybe it's just certain items or something?

**Comment by chairbender** [comment] 2019-03-24 22:53
Be aware we've only reproduced it on the steam client / server so far.

**Comment by Aranclanos** [comment] 2019-03-28 03:31
Still can't reproduce, can you give more details of how it exactly happened?

**Comment by chairbender** [comment] 2019-03-28 03:34
We were playing on the steam server, Bod threw some sort of canister thing at me I instantly went into crit and died a few seconds later. Bod confirmed that throwing does way too much damage so I assumed this is an actual issue.

Maybe it isn't anymore.

**Comment by chairbender** [comment] 2019-03-28 03:35
...or maybe it's only certain thrown items that do it?

**Comment by Bod9001** [comment] 2019-03-30 11:14
ok, The problem was the characters being hit multiple times After the restart it didn't appear again, On my end the item went through the character  Then once the character died it Teleported
 back to where it should be

**Comment by fomalsd** [comment] 2019-04-01 13:29
Fishfish once posted a gif with an effect similar to what you describe. it was an experiment though, hit code was modified then.
![damaage](https://user-images.githubusercontent.com/10403536/55331265-6cd6aa00-5482-11e9-9195-a2014bf58edd.gif)

**Comment by Bod9001** [comment] 2019-04-01 14:07
That's pretty much what happened

**Comment by chairbender** [comment] 2019-04-06 23:33
maybe it has to do with object pooling - an object having some sort of impartially reset state when being spawned to be thrown

**Comment by Aranclanos** [comment] 2019-05-16 11:32
I'd like to close this, never saw it happen. (but with the new atmos wind but thats unrelated)

**Comment by fomalsd** [comment] 2019-05-16 11:41
Yeah, reopen it if it ever happens again

**Closed as completed by fomalsd** 2019-05-16 11:41 UTC
Labels: Type: Bug, Bounty, Affects only: Headless, Status: Needs Reproduction
