### ISSUE TITLE
Objects stop being pulled after you run into something

### ISSUE THREAD

**Issue by Alekshhh** [unitystation/unitystation#8787] opened 2022-06-06 15:31 UTC
### Environment
- Game Version: 22060401
- OS Version: win10

### Detailed description of bug

When pulling something, running into any solid object causes you to stop pulling it.

### Steps to reproduce

1. Pull something
2. Run into a wall
3. Cry (optional)

**Comment by ThatDan123** [comment] 2022-07-19 22:16
Cant reproduce on staging, must have been fixed. So closing

**Closed as completed by ThatDan123** 2022-07-19 22:16 UTC
Labels: Type: Bug, Group: Movement
