### ISSUE TITLE
taking damage from using internals

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7697] opened 2021-11-01 03:43 UTC
### Environment
- Game Version: Staging 21102918
- OS Version: Arch Linux

### Detailed description of bug

when you turn on the internals you take around 2 oxy damage continually

https://user-images.githubusercontent.com/80334192/139618729-cedd9888-87a9-4364-8ac6-2296315f1c36.mp4

### Steps to reproduce

1. use internal
2. spam health analizer

**Comment by MaxIsJoe** [comment] 2021-11-01 03:57
I actually fixed this issue but it got rejected

**Comment by MaxIsJoe** [comment] 2021-11-01 03:59
#7667 was the fix but Dan insisted on just using gasMix instead of internal gases so i thought "well alright then"

**Comment by ThatDan123** [comment] 2021-11-01 12:11
> I actually fixed this issue but it got rejected

> #7667 was the fix but Dan insisted on just using gasMix instead of internal gases so i thought "well alright then"

Thank you for accusing me for blocking your fix which would've have done nothing as we were already getting the correct gasmix, and that I even went through with you for how the code works for getting the gasmix.

Your fix would've the same issue of oxygen damage and unlike you before accusing someone I decided to debug and found that the player breathes out into their tank which increases the CO2 moles thus higher CO2 pressure which goes above the limit very quickly so triggers the toxins damage.

So to fix this we might need to change the toxins pressure check to a moles check, or change it so we always breathout into the node not the internals gasmix

 Please next time consider fully investigating the issue before blaming someone

**Comment by MaxIsJoe** [comment] 2021-11-01 14:57
> > I actually fixed this issue but it got rejected

> Please next time consider fully investigating the issue before blaming someone

First of; I didn't "accuse you" of blocking a fix, I'm saying that you rejected a fix that prevented this issue so we can do things the correct way and the reason as to why i ignored it even though i was fully aware of the oxygen problem since the very first PR is because it's such a non-issue and I only pointed out that fix here so if anyone wants to look at fixing the issue they could look at what i did to prevent it before even if it's "not the correct way"

And I've stated at least twice on github and discord that this issue happens if you remove that `if` check that I put there, nobody probably noticed it because logically via the code you think it wouldn't happen and from testing the 2 points of damage aren't that noticeable unless you stare at your health doll and notice it going green to blue and vice versa every few seconds which my fix prevented.

**Comment by PetMudstone** [comment] 2021-11-02 00:55
I was able to reproduce on staging. Strangely, I didn't seem to have this problem while first using internals at the start of the round. It was only after I died and tried using internals again that I started taking suffocation damage.

**Comment by ThatDan123** [comment] 2021-11-02 21:01
Fixed by #7652

**Closed as completed by ThatDan123** 2021-11-02 21:01 UTC
Labels: Type: Bug, System: Damage
