### ISSUE TITLE
It's possible to move through walls and get stuck in doors/walls

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2756] opened 2020-01-27 02:40 UTC
It's possible to move through walls and get stuck in doors/walls

It's not a frequent occurence and seems to be related to lag.

I think it **might** have something to do with a queue of messages not being processed yet by the server.  You can probably enqueue invalid directions, and then, when the server process them, you changed position/direction and dequeue them, sending you right through an invalid passage.

Steps to Reproduce
1.  If you have more info, please share.

**Comment by DooblyNoobly** [comment] 2020-01-27 07:39
This happened in the same round that I experienced #2755. I believe the cause was some severe NRE's on the server that happened earlier on, which caused all of this unwanted movement behavior. Closing this issue. Will reopen if it reappears.

**Closed as completed by DooblyNoobly** 2020-01-27 07:39 UTC
Labels: Type: Bug, System: Movement, Group: Networking
