### ISSUE TITLE
Server performance is insanely poor

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#7565] opened 2021-10-12 23:16 UTC
### Environment
- Game Version: 21101020 (latest at the moment of writing)
- OS Version: Win10 (client), Ubuntu server 18 (host)

### Detailed description of bug
Server FPS is insanely low even with low pop and nothing extraordinary happening. Thanks to Aranclano's recent PR, we can measure it at real time and notice how the server sits at around 5-10 fps

![image](https://user-images.githubusercontent.com/43683714/137041283-c5c12011-d20c-4d5c-bc9d-dac01d11645c.png)

The repercusions of this can be experienced in many ways, as in poor responsiveness in validated actions like moving objects in your inventory, opening doors, traveling inside disposals loops and rubberbanding.

The causes of the issue are, as far as I know, unknown.

### Steps to reproduce
1. Join Staging
2. Check the stats tab
3. Doesn't really matter if it is a fresh new round, ongoing round or the third one.

**Comment by RedlineTriad** [comment] 2021-10-29 22:34
Is this a duplicate of #3177 or should one be merged into the other?

**Comment by corp-0** [comment] 2021-10-29 22:37
it is a different issue. #3177 is from a time when we had good performance and it degraded over time. Right now we just have bad performance, as stated in the description, no matter if it is the first round after a fresh reset.

**Comment by PerfectTangent** [comment] 2022-02-15 13:33
While I think our performance still isn't desireable, and it degrades overtime as described in #3177, I think this issue can be closed.

![Screenshot 2022-02-15 083057](https://user-images.githubusercontent.com/68730437/154072162-e39b43c9-61e3-414e-8514-b9a45cdfd693.jpg)

Server performance on a _fresh round_ with _minimal players_ on staging EU has improved dramatically.

**Closed as completed by PerfectTangent** 2022-02-15 13:33 UTC
Labels: Type: Bug, Type: Performance
