### ISSUE TITLE
Admin spawn of grenade prefab crash connected clients

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#4889] opened 2020-08-16 19:51 UTC
## Description
Title. No idea what is so special in grenade prefab. Client just freeze and can be killed only by task manager.
Using connected debuger it seems that server send a lot of spirte changes packets. Maybe it loops client to death.

### Steps to Reproduce
1.  Connect client to server
2.  Spawn grenade using admin tools

**Comment by PerfectTangent** [comment] 2021-02-21 21:42
I have been unable to reproduce this issue. Closing for now unless we get a new report.

**Closed as completed by PerfectTangent** 2021-02-21 21:42 UTC
Labels: Type: Bug
