### ISSUE TITLE
Stabbing animals as client produces NRE on server side

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#834] opened 2018-01-08 14:59 UTC
# Preliminary information

## Category
BUG

## Bug: Release or Development?
latest develop

# Report
## Current Behavior
Server getting following exception when high ping client stabs animals, effects are unknown:
`NullReferenceException: Object reference not set to an instance of an object
WeaponNetworkActions.CmdKnifeAttackMob (UnityEngine.GameObject npcObj, UnityEngine.GameObject weapon, UnityEngine.Vector2 stabDirection, BodyPartType damageZone) (at Assets/Scripts/Weapons/WeaponNetworkActions.cs:149)
WeaponNetworkActions.InvokeCmdCmdKnifeAttackMob (UnityEngine.Networking.NetworkBehaviour obj, UnityEngine.Networking.NetworkReader reader) (at <2ac6b71c782745a984717660238cce30>:0)
UnityEngine.Networking.NetworkIdentity.HandleCommand (System.Int32 cmdHash, UnityEngine.Networking.NetworkReader reader) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkIdentity.cs:618)
UnityEngine.Networking.NetworkServer.OnCommandMessage (UnityEngine.Networking.NetworkMessage netMsg) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:1281)
UnityEngine.Networking.NetworkConnection.HandleReader (UnityEngine.Networking.NetworkReader reader, System.Int32 receivedSize, System.Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkConnection.cs:469)
UnityEngine.Networking.NetworkConnection.HandleBytes (System.Byte[] buffer, System.Int32 receivedSize, System.Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkConnection.cs:425)
UnityEngine.Networking.NetworkConnection.TransportReceive (System.Byte[] bytes, System.Int32 numBytes, System.Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkConnection.cs:576)
UnityEngine.Networking.NetworkServer.OnData (UnityEngine.Networking.NetworkConnection conn, System.Int32 receivedSize, System.Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:738)
UnityEngine.Networking.NetworkServer+ServerSimpleWrapper.OnData (UnityEngine.Networking.NetworkConnection conn, System.Int32 receivedSize, System.Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:1869)
UnityEngine.Networking.NetworkServerSimple.HandleData (System.Int32 connectionId, System.Int32 channelId, System.Int32 receivedSize, System.Byte error) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServerSimple.cs:384)
UnityEngine.Networking.NetworkServerSimple.Update () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServerSimple.cs:247)
UnityEngine.Networking.NetworkServer.InternalUpdate () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:691)
UnityEngine.Networking.NetworkServer.Update () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkServer.cs:642)
UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkIdentity.cs:1091)
`

## Expected/Wanted/Requested Behavior
Want no exceptions around!

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. host as editor, join as build with 200ms ping simulation
2. get a knife and stab some animals (might not show up on the very first time)

## Network
Net simulation, "200ms"

**Comment by fomalsd** [comment] 2018-01-08 15:07
It seems to

**Comment by fomalsd** [comment] 2018-01-19 07:17
I still had it when testing my #851 PR

**Comment by chairbender** [comment] 2019-01-02 05:50
I can't reproduce this anymore, even with the specified ping. Considering it's a year old now I'm going to say it's safe to close. The way weapons works is quite a bit different now, the method referenced in the stack trace doesn't even exist anymore.

**Comment by chairbender** [comment] 2019-01-02 05:51
oops, I should probably make sure @fomalsd gets one last look at it before deciding to close.

FYI @fomalsd I can't reproduce this anymore. Go ahead and close if you're fine with it.

**Comment by chairbender** [comment] 2019-01-03 22:47
Got the go ahead from foma to close it

**Closed as completed by chairbender** 2019-01-03 22:47 UTC
Labels: Type: Bug
