### ISSUE TITLE
AI has no access to any consoles

### ISSUE THREAD

**Issue by mmails** [unitystation/unitystation#8238] opened 2022-01-28 10:28 UTC
### Environment
- Game Version: Latest staging version
- OS Version: Windows 10

### Detailed description of bug

AI doesn't have access to any consoles, APUs, ACUs, etc etc due to them being ID locked

### Steps to reproduce

1. Play as AI
2. Go to any console
3. Profit

**Comment by ThatDan123** [comment] 2022-01-28 11:41
Duplicate of #7172

**Closed as completed by ThatDan123** 2022-01-28 11:41 UTC
Labels: Type: Bug
