### ISSUE TITLE
Behaving normally when in Critical Health

### ISSUE THREAD

**Issue by alex180500** [unitystation/unitystation#1062] opened 2018-05-13 13:45 UTC
# Preliminary information

## Category
Bug

## Bug: Release or Development?
Latest release but I think it works on Development too

# Report
## Current Behavior
When in critical health you can go everywhere and behave normally as in normal health.

## Expected/Wanted/Requested Behavior
You should stay on the floor where you are and dying

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Go outside the station and start taking damage, I think it works for every role but i tried only with syndicate.
2. In the exact moment you get to critical health come back to the station
3. Start the free roam

## Video with the reproduction of the bug
https://youtu.be/-WxBt3V634k

## OS used:
Windows

## System specifications
R3 1200, RX 580, 8gb ddr4 ram.
But i don't think it's a system problem.

## Network
I local hosted it

**Comment by fomalsd** [comment] 2018-05-15 18:41
can't view that video for some reason...

**Comment by alex180500** [comment] 2018-05-15 18:43
Try again now, i set up public privacy

**Comment by Itsnotjames** [comment] 2018-10-16 01:27
Can't reproduce this bug, looks like its fixed.

**Comment by DooblyNoobly** [comment] 2018-10-16 01:56
Thanks, I think I may of fixed this when making adjustments to melee stuff. Bug happened when player was returning back to his position after a melee lerp and therefore setting AllowedMovement flag back to true. Closing this now

**Closed as completed by DooblyNoobly** 2018-10-16 01:56 UTC
Labels: Type: Bug
