### ISSUE TITLE
Becoming bald after equipping hardsuit helmet

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#6925] opened 2021-07-03 14:50 UTC
![losing hair gif](https://user-images.githubusercontent.com/701959/124358049-de1edd80-dbf4-11eb-8f5e-3271d6b20745.gif)

tested on latest develop on editor

**Comment by MaxIsJoe** [comment] 2021-10-28 01:03
Tested it, does not happen anymore.

**Comment by PerfectTangent** [comment] 2022-01-24 10:51
Going to close this issue, as I can't reproduce either. It's likely (hopefully) been fixed.

**Closed as completed by PerfectTangent** 2022-01-24 10:51 UTC
Labels: Type: Bug, lol, System: Animation
