### ISSUE TITLE
Inventory can mess up

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1699] opened 2019-04-03 07:03 UTC
# Description
had inventory fail on me in a weird way:
![Scr 2019-04-03 в 0 36 11 2019-04-03 10_01_11](https://user-images.githubusercontent.com/10403536/55459129-77668000-55f7-11e9-9d00-edc31771b4b9.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
**Was unable to reproduce it again**, but what I did was:
1. Launched game from Outpost scene and joined as miner
2. Walked around station and across matrices, equipped and unequipped mask, finally got ejected into space in crit
3. Killed myself with a "Kill local player" command and respawned (a couple of times)

**Comment by Fishfish458** [comment] 2019-04-03 08:40
I'll try to look into this one because I think I know the systems involved.  though I'd like to know if someone does reproduce it again if it's rare.

**Comment by fomalsd** [comment] 2019-04-23 12:03
https://cdn.discordapp.com/attachments/443317202179981322/569261880644861962/stuck_inv.gif
Reproduced by @chairbender on steam server. Exact steps are still unknown though

**Comment by chairbender** [comment] 2019-11-10 23:27
Might be fixed with #2245

**Closed as completed** 2019-11-11 07:34 UTC
Labels: Type: Bug
