### ISSUE TITLE
Suits hide beards

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1753] opened 2019-04-16 12:12 UTC
# Description
![image](https://user-images.githubusercontent.com/701959/56208472-9cabb300-6027-11e9-9c34-a6c12670dd56.png)
Your suit will appear on top of your beard suit, it also happens with exosuits

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Get a character with a long beard
2.Wear a suit
3.Notice how part of the sprite is hidden by your suit

**Comment by fomalsd** [comment] 2019-04-16 12:14
Duplicate of #1752

**Closed as completed by fomalsd** 2019-04-16 12:14 UTC
