### ISSUE TITLE
[BUG] no hachet on botany

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10525] opened 2024-09-14 11:35 UTC
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

24 07 27 17

### I was

Client

### OS

Windows 8, 10, 11

### What happened?
i has hop, fallstation

in the lockers and more seriously in the admin spawn menu there is no axet
which is essential for certain crafts.

What's more, with a stack of boards in hand, the wooden barrel doesn't appear.

### What should have happened instead?

A hatchet should be present in each caseion and should be purchasable at the cargo or craftble.

### Steps to reproduce the issue

be a botanist,
open locker
nothing

**Comment by MaxIsJoe** [comment] 2024-09-15 16:41
duplicate of #10471
please only report issues once

**Closed as completed by MaxIsJoe** 2024-09-15 16:41 UTC
Labels: Type: Bug

**Comment by Fr-Dae** [comment] 2024-09-15 16:43
Hello it's a different bug 
it's not just a mapping issue, the object simply doesn't exist in the list of spawn admin objects

**Comment by Fr-Dae** [comment] 2024-09-15 16:43
in addition, that not solve the issue for wodden barrel

**Comment by MaxIsJoe** [comment] 2024-09-15 16:52
![image](https://github.com/user-attachments/assets/0f087821-f863-46d6-b4ef-723969b50ade)


> Hello it's a different bug it's not just a mapping issue, the object simply doesn't exist in the list of spawn admin objects

That's because you're misspelling it.

**Comment by Fr-Dae** [comment] 2024-09-15 16:58
and in fallstation ?

**Comment by MaxIsJoe** [comment] 2024-09-15 17:08
> and in fallstation ?

![image](https://github.com/user-attachments/assets/eb7b67b3-0617-4f9e-bb8f-a7102b7032ca)

**Comment by Fr-Dae** [comment] 2024-09-15 17:12
OK,my bad 
 I think I've got a problem with my version, I'll have to update it.
