### ISSUE TITLE
Dead/crit players get back up when stun is over

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2407] opened 2019-12-02 11:47 UTC
# Description
![image](https://user-images.githubusercontent.com/10403536/69956888-32357d80-14f9-11ea-8b89-91dfb992210e.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Beat yourself up a bit
2. Explode large tanks nearby to get stunned and hit by a few objects to crit/die
3. See your dead/unconscious player get back up after a while

**Comment by chairbender** [comment] 2019-12-08 23:38
nvm though I saw this happening in other situations but I see this ticket covers them

**Comment by chairbender** [comment] 2019-12-12 23:59
would like to add, on client side, I see lots of cases where dead players never even show up laying down, they just die standing up.

**Comment by fomalsd** [comment] 2020-01-26 12:26
This is a thing again

**Comment by fomalsd** [comment] 2020-01-26 13:12
![i](https://user-images.githubusercontent.com/10403536/73135721-99cdfc00-4056-11ea-9dd9-cc1aa535e052.gif)

**Comment by chairbender** [comment] 2020-01-27 21:34
ah, so the reproduction is getting knocked down and then getting killed. It's making you stand back up again due to the timer that was set when you first were knocked down which stands you back up when timer is done. I think all that's needed here is adding a check for those various things that can knock you down so that whatever they are calling to stand you back up doesn't occur if player is dead.

**Comment by JesterX666** [comment] 2020-02-01 12:22
Fixed by PR #2801

**Closed as completed by JesterX666** 2020-02-01 12:22 UTC
Labels: Type: Bug, Good First Issue, lol
