### ISSUE TITLE
machine connectors seem to be duplicated by unwrenching them.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#7554] opened 2021-10-10 11:02 UTC
### Environment
- Game Version: latest staging

### Steps to reproduce

1. find a placed machine connector
2. unwrench it

**Comment by MaxIsJoe** [comment] 2021-10-27 18:58
I can't seem to replicate this, can anyone confirm if they're having the same issue and how they're doing it?

**Comment by MaxIsJoe** [comment] 2021-10-27 23:54
Note : doesn't seem to be happening on staging either when I tested it.

**Comment by Leander-0** [comment] 2021-10-28 01:51
im sure you cant unwrench machine connector but cut them out of the floor, i replicated it by spawning the syndicate base (respawn as nuke ops) on squarestation and going to main station and disconnect the machine connector.


https://user-images.githubusercontent.com/80334192/139172339-b1fe5915-1a1d-4704-b1ec-eacba14fd4fe.mp4

**Comment by ThatDan123** [comment] 2021-11-02 21:58
> im sure you cant unwrench machine connector but cut them out of the floor, i replicated it by spawning the syndicate base (respawn as nuke ops) on squarestation and going to main station and disconnect the machine connector.
> 
>  machine.mp4

Can be reproduced in the editor, all you need to do is spam click the wire cutters on the machine connector tile.

Think its due to the delay between the tile being removed and the action, not sure whats the best way to fix this.

**Comment by MaxIsJoe** [comment] 2022-04-15 00:13
still unable to replicate this

**Comment by NoooneyDude** [comment] 2022-04-15 00:15
I think it occurs when the electrical system is on the fritz (which might be fixed now?)

**Closed as completed** 2022-05-10 08:10 UTC
Labels: Type: Bug, System: Construction
