### ISSUE TITLE
Clients having problems with lights, APCs, and wires rotations

### ISSUE THREAD

**Issue by badbon** [unitystation/unitystation#1405] opened 2018-12-28 06:08 UTC
# Description
Was bored so did tiny bit of investigation. I was told some other people haven't seen it and couldn't reproduce so this might have to be closed but oh well, still weird.

Basically, when you join as a client (when other game instance hosts) lights, wall mounts, wires, etc are randomly rotated around. Here's screenshots:

https://i.gyazo.com/6359c1924e30296a0c6d2a9cf1b52d1b.png
https://i.gyazo.com/f9178eb9b7032744661686b78c67fc64.png

## Category
BUG

## Detailed Bug Report
See above.
## Steps to Reproduce
1. Build a game, host on one of them (Doobly said it only happens on editor, but it didn't matter for me, both editor and game build seem to be broken on my side, whichever is client at least)
2. Join from other, pick assistants as both to compare.
3. You can see wires in maintance are off, and lights may or may not be off because they are rotated around.

**Comment by fomalsd** [comment] 2018-12-28 06:15
if all of them had a CustomNetTransform component it wouldn't have been a problem, but they **shouldn't need** to have one!

**Comment by DooblyNoobly** [comment] 2018-12-28 08:13
would be good to see your logs from your builds. Are you building with lobby scene as well?

**Comment by fomalsd** [comment] 2018-12-28 08:14
also how fast is machine you're testing it on? +is ping simulation used?

**Comment by badbon** [comment] 2018-12-28 10:15
Yes I am building with lobby scene. 

Ryzen 5 1600 on local host

**Comment by DooblyNoobly** [comment] 2019-01-05 23:55
working fine in Steam builds

**Comment by chairbender** [comment] 2019-01-05 23:57
Oh, glad to see someone else experiencing this. 

I get this on the client side when hosting in editor and joining as client from the player. I don't get it on client or host side when hosting in player and joining as client from editor.

The issue I'm working on right now #894  also has a similar problem - it only happens when joining as a client from the player but not joining as client from the editor.

**Comment by chairbender** [comment] 2019-01-25 06:20
Might be related to #1237, I am noticing some quirks related to rotation logic

**Comment by chairbender** [comment] 2019-01-26 22:00
Let me know if anyone experiences this (once #1466 is merged). I am hopeful that my changes will fix this issue. Or else it is already fixed due to something else.

**Comment by chairbender** [comment] 2019-01-29 16:48
This definitely still happens:

![randomrotation](https://user-images.githubusercontent.com/1329062/51924820-98fe7d80-23a2-11e9-9eea-c629a6a82df9.gif)

**Comment by chairbender** [comment] 2019-02-05 23:24
I am only noticing this when I get the "black text issue" in the editor as server (lobby text shows up black rather than white), which apparently means something went wrong with unity / the build and isn't really caused by our code.

**Closed as completed** 2019-04-08 05:14 UTC
Labels: Type: Bug, Status: In Progress, Status: Needs Reproduction
