### ISSUE TITLE
Secret walls aren't very secret

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9121] opened 2022-08-13 19:57 UTC
![image](https://user-images.githubusercontent.com/34368774/184508907-5d7bf15a-42f1-407c-8c2d-dfe4f242297d.png)

**Comment by NoooneyDude** [comment] 2022-08-22 06:20
Duplicate of #4746.

**Closed as completed** 2022-08-23 20:32 UTC
Labels: Type: Bug
