### ISSUE TITLE
Oxygen internals turn off during some actions such as pulling.

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#3048] opened 2020-02-11 17:06 UTC
Turn on your internals, then pull someone, loot someone, open a backpack. Usually one of these scenarios lead to my internals turning off.

Could be due to lag.

**Comment by NoooneyDude** [comment] 2020-07-23 07:48
I can't reproduce this, and haven't noticed any complaints about this in Discord. It might be worth closing unless we can get better reproduction steps.

**Closed as completed** 2020-07-31 19:27 UTC
Labels: Type: Bug, Status: Needs Reproduction
