### ISSUE TITLE
Space deals no damage

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#2093] opened 2019-08-09 16:53 UTC
# Description
Walk to space and you'll find that the atmosphere does not affect you, you do not take freezing damage or lose breath

## Category
BUG

## Detailed Bug Report
I dont know why, but the MatrixManager.GetMetaDataAt( worldPosition ) function which returns the node with the gasmix information, is always returning one with a normal atmosphere, so you breath normally and stay at a good temperature

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.walk into space
2.stay at 100% health

**Comment by fomalsd** [comment] 2019-08-09 17:35
Duplicate of #2073

**Closed as completed by fomalsd** 2019-08-09 17:35 UTC
