### ISSUE TITLE
Computer overlays on clients doesnt toggle on

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#2014] opened 2019-07-09 12:55 UTC
# Description
![image](https://user-images.githubusercontent.com/701959/60889450-66995c00-a22f-11e9-8d55-bdb4a3fc4c3d.png)
top: server
bottom: client

Notice how the computer overlay sprite doesnt show up on the client.
note: this only happens when power goes off and on, when joining for the first time the overlay will be on

## Category
BUG

**Comment by chairbender** [comment] 2019-09-02 23:41
possible duplicate of #2126

**Comment by fomalsd** [comment] 2019-09-02 23:55
in #2126 they're black on serverside, too

**Closed as completed** 2019-09-05 10:39 UTC
Labels: Type: Bug, Status: In Progress
