### ISSUE TITLE
Ancient engineering is able to hear the main station being destroyed

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6783] opened 2021-06-11 19:37 UTC
ideally the station being damaged should have a limit to how far the sound can be heard, i mean it's space, cmon

sound should check for if localplayer is on station that's taking damage, or on a matrix colliding with station taking damage before making noise

**Comment by pyrosshade** [comment] 2021-06-11 19:47
this should also apply to anyone who hasn't joined round yet, they currently can hear the station crashing as well

**Comment by Bod9001** [comment] 2021-06-11 20:04
wasn't able to replicate on editor but could be some sounds being global when they shouldn't be

**Comment by Bod9001** [comment] 2021-06-11 20:04
(I was trying to rig explosion then popping into body on ancient engineering station)

**Comment by PerfectTangent** [comment] 2021-06-12 01:40
Sounds like a duplicate of #4578. Closing.

**Closed as completed by PerfectTangent** 2021-06-12 01:40 UTC
Labels: Type: Bug
