### ISSUE TITLE
Gibbing one of your old bodies will turn you into a ghost if you are cloned B: 30

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3165] opened 2020-02-17 08:08 UTC
If one of your dead bodies after cloning is gibbed then you will turned into a ghost.

Make sure this doesn't happen

**Comment by fomalsd** [comment] 2020-02-17 08:13
Duplicate of #2989, but will close the earlier one since this one has a bounty attached

**Closed as completed** 2020-02-17 08:52 UTC
Labels: Type: Bug, Bounty, Priority: High
