### ISSUE TITLE
Entering the pressure value on tanks gets you stuck

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#2881] opened 2020-02-04 14:31 UTC
Description

### Detailed Bug Report
* Happened on Ger server
* restarting client fixes the issue

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Find tank and change value manually by typing it in.
2.  close window
3.  cant move, chat or open menu.

**Comment by JesterX666** [comment] 2020-02-09 18:55
Not reproduced.  Working fine in USA03 right now.
Are you clicking on the field with the mouse?  Are you closing the window with the X?  Is there some key involved like "TAB" or something else?

**Comment by NoooneyDude** [comment] 2020-07-23 05:56
I couldn't reproduce this either. I think it was fixed in general by one of the PRs, though I can't find it. Can probably close this.

**Closed as completed** 2020-07-31 19:23 UTC
Labels: Type: Bug, Status: Needs Reproduction
